### ISSUE TITLE
Support for ggplot2 pins

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/pins#108]

**Comment by colearendt** [comment]
Worth noting that plots are a generic type of static content on RStudio Connect. (i.e. comparable to a pin). While I'm not opposed to using the "pin" package to generate such a plot and deploy it, I wonder if it starts to blur a boundary around "what is a pin" and "what is a plot." I.e. could you "pin" a static HTML document too?

![image](https://user-images.githubusercontent.com/23075542/70675030-e51e7d80-1c55-11ea-89ae-f3f64199e859.png)

**Comment by aronatkins** [comment]
A "plot" as deployed to RStudio Connect by the IDE is really just a single HTML file with embedded base64 image data. Both plots and pins are part of the more general "static content" classification, which means that Connect serves content as it was uploaded -- it cannot be regenerated by the server and source is not included.

Pins are a collection of reusable assets (data files, images, etc) and instructions about how to use those assets. I can see an argument for images as pins (or one asset in a collection of files in a named pin). I can also see images created as a side-effect of running an R Markdown document (marked as an output file) or included alongside some HTML document.

I don't think that there's one answer; plots can be distributed in a number of ways. When the image is treated as data, having it part of a pin feels appropriate.

**Comment by javierluraschi** [comment]
Right, let's close this for now. First, not many users are using pins to cache plots, and second, if we do probably worth figuring out if there is overlap with the plot concept and how that can be best resolved.
