### ISSUE TITLE
Several issues with github board with path (subdirectory) specified.

### ISSUE THREAD

**Issue by RandomCriticalAnalysis** [rstudio/pins#119]
There are several issues with pins on board created on github with a path (subdirectory) specified.  These issues do not seem to happen if the board is created directly in the repo root.  For example, when a pin is created in the board with subdir/path, it won't list the path in Rstudio, show in pin_find(), delete with pin_remove(), and so on.   I was able to sort-of delete by passing the subdirectory as part of the pin name, but that doesn't work entirely either.   

Thanks

**Comment by javierluraschi** [comment]
Various fixes available in devel version and soon in CRAN, you can install and verify fixes with:

```
remotes::install_github("rstudio/pins")
```
