### ISSUE TITLE
Include timestamp in pin_info()

### ISSUE THREAD

**Issue by andrie** [rstudio/pins#134]
I want to include a pinned dataset as part of my workflow, and thus would like to be sure that my pin was updated.

As far as I can tell, the timestamp is not available in `pin_info()` or any other function.

This is a feature request to include the last updated timestamp in the pin information.

**Comment by colearendt** [comment]
I implemented a version of this for `rsconnect` that seems to work well. However, I'm not sure whether this is a generic solution for all boards.

```r
pin_last_updated <- function(name, board) {
  as.POSIXlt(pin_info(name = name, board = board)$last_deployed_time, format = "%Y-%m-%dT%H:%M:%SZ")
}
```

**Comment by javierluraschi** [comment]
Right, `last_deployed_time` is the closest RSC provides:

```r
pins::pin_info("test", board = "rsconnect")
```
```
# Source: rsconnect<javierluraschi/test> [files]
# Description: A files pin with txt extension.
# Properties:
#   - id: 524
#   - guid: 9a7f558b-2b37-4e25-8200-d330956ab34c
#   - access_type: acl
#   - url: https://connect.rstudioservices.com/content/524/
#   - vanity_url: FALSE
#   - bundle_id: 3004
#   - app_mode: 4
#   - content_category: pin
#   - has_parameters: FALSE
#   - created_time: 2019-12-11T19:21:40Z
#   - last_deployed_time: 2019-12-11T19:22:23Z
#   - build_status: 2
#   - run_as_current_user: FALSE
#   - owner_first_name: Javier
#   - owner_last_name: Luraschi
#   - owner_username: javierluraschi
#   - owner_guid: 38f53f50-1a1f-4676-9176-ea3996fb97ef
#   - owner_locked: FALSE
#   - is_scheduled: FALSE
#   - path: test.txt
#   - extension: txt
```

I think we can close this one, correct?

**Comment by andrie** [comment]
It will be really helpful if you include this information in the return value for `?pin_info`

**Comment by colearendt** [comment]
I think the idea I had was a generic function that returns the last time a pin was modified. I presume you're doing something generic to this effect with `pin_reactive()`? Using a `last-modified` header or something? This would give someone doing their own `memoise` implementation the generic tool necessary to do so.

Ultimately my concern with `last_deployed_time` is that it is `rsconnect` specific and not generically guaranteed to work w/ pins.

**Comment by javierluraschi** [comment]
@andrie @colearendt yeah, so by default `pins` uses the `etag` header, which does not seem to be provided by RStudio Connect so we use instead the `last_deployed_time` column, see https://github.com/rstudio/pins/blob/b578a8ca81aca1feee5af8e8ba5120f1c00b2b29/R/board_rsconnect.R#L227.

So in general, `pin_reactive()` should do all this work for you, if not, please pass a reprex to investigate further!

**Comment by javierluraschi** [comment]
Looks like we have a resolution here, if not please open new bug, closing!
