### ISSUE TITLE
Allow `pin_find` to show all pins accessible to users on RSC

### ISSUE THREAD

**Issue by akgold** [rstudio/pins#135]
Currently it only returns pins actually made by a particular person, as opposed to all they have access to.

**Comment by javierluraschi** [comment]
Fixede in `pins 0.3.0`, see http://pins.rstudio.com/news/index.html#rstudio-connect:

- Fix issue where pin_find() would not show all available pins.

**Comment by javierluraschi** [comment]
Fixing, but please open a new issue if for some reason this is still a problem, thanks!
