### ISSUE TITLE
Suggestion: Have visibility of pin file size

### ISSUE THREAD

**Issue by kmasiello** [rstudio/pins#136]
Provide a means to determine pin file size so the disk space usage can be monitored and the optimal means for storing data can be evaluated.

**Comment by javierluraschi** [comment]
For the `rsconnect` board:

> rsconnect enforces a limit on the maximum bundle size based on the `rsconnect.max.bundle.size` option, this maximum can be set on the client and I believe would have the side affect of enforcing a max size on the pin. 
>
> RStudio Connect includes a setting that will limit how many content bundles (uploaded pins) are retained on the server for a given endpoint.  This setting is set in the config file, for example:
>
>```yaml
>[Applications]
>BundleRetentionLimit=3
>```

**Comment by javierluraschi** [comment]
`BundleRetentionLimit` in combination with monitoring `pin_info()` seems like the most reasonable approach for now. If we have additional suggestions, worth opening a new github issue labeled "feature request".
