### ISSUE TITLE
Add option for memoised caching

### ISSUE THREAD

**Issue by colearendt** [rstudio/pins#140]
I'm not sure whether this is something that would be possible to include in the package. It's not clear to me how `cache = TRUE` works, but it would be nice to have some control over that. I.e. maybe take a `memoise::cache_filesystem()` argument or something (Related to #134 and #95).

Adding a dependency (or at least a `Suggests` dependency w/ some checks) on `memoise` in this naive implementation:

```
# implemented by #134 ?
pin_last_updated <- function(name, board) {
  as.POSIXlt(pin_info(name = name, board = board)$last_deployed_time, format = "%Y-%m-%dT%H:%M:%SZ")
}

# downside... this only memoises a particular pin_get
memoise_pin_get <- function(name, board, cache = memoise::cache_memory()) {
  memoise::memoise(
    function() pin_get(name = name, board = board, cache = FALSE),
    ~ pin_last_updated(name = name, board = board),
    cache = cache
  )
}

mypin <- memoise_pin_get("iris", board = "rsconnect", cache = memoise::cache_filesystem(".pin_cache"))

# use
mypin()
```

This helps with persistence across R sessions, performance / redundancy if a pin does not update often, could help with the offline context in #95 , etc.

**Comment by javierluraschi** [comment]
Thanks for the suggestion, at this point, `pins` implements its own cache, so unless I'm misunderstanding, I believe there is no need to use `memoise`.
