### ISSUE TITLE
install `zip` automatically?

### ISSUE THREAD

**Issue by skeydan** [rstudio/pins#15]
Should `pins` try to install `zip`?

```
==> R CMD INSTALL --no-multiarch --with-keep.source pins

* installing to library ‘/home/key/R/x86_64-redhat-linux-gnu-library/3.6’
ERROR: dependency ‘zip’ is not available for package ‘pins’
```

**Comment by javierluraschi** [comment]
I believe this problem would go away once we install from CRAN, so I think we can close... or reopen in the `rstudio` repo if we really feel like doing more work in the IDE>
