### ISSUE TITLE
Can't pin tibble that contains list columns

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#157]
Hi,

I get the following error if I try to pin a tibble that contains a list.

     a<-tibble(my_list=list("a"="b"))
     pin(a,name="test",board = 'rsconnect')

    Error in write.table(x, file.path(path, "data.csv"), row.names = FALSE,  : 
    unimplemented type 'list' in 'EncodeElement'

Thanks

Iain

**Comment by javierluraschi** [comment]
Hi @iainmwallace, thanks for using pins!

Could you try updating to the latest version of `pins`? As in,

```
install.packages("pins")
```

Thanks!

**Comment by iainmwallace** [comment]
Thanks, that worked!
