### ISSUE TITLE
unexpected errors in using github board with large files

### ISSUE THREAD

**Issue by cboettig** [rstudio/pins#168]
Love the design of this package and really excited to adopt it in my workflows. Have wanted something just like this for a long time!

Trying to upload a local file to a GitHub board that is in a subdirectory creates the error:

```r
pin("2020/dwc_gbif.tsv.bz2", 
+     description = "2020-02-04 cache of GBIF Taxonomic Names in Darwin Core", 
+     board = "github")
```

```
Error in curl::form_file(path, type) : is.character(type) is not TRUE
```

I then switch into the sub directory and I get a bit further but still no actual upload, just another error:

```r
pin("dwc_gbif.tsv.bz2", 
+     description = "2020-02-04 cache of GBIF Taxonomic Names in Darwin Core", 
+     board = "github")
```

```
Error in github_create_release(board, name) : 
  Failed to create release 'dwc_gbif_tsv-9324616' for 'dwc_gbif_tsv': Validation Failed
```
I can see a new release has been created (as expected, since this is a large file), but no data file is attached.  (probably due to the validation error mentioned)

Any suggestions on debugging would be appreciated!  (errors above occur with both the CRAN version and current GitHub version)

**Comment by javierluraschi** [comment]
Lemme take a look... the second error can probably be fixed if you specify the name for the pin explicitly, there are some restrictions on naming releases....

**Comment by cboettig** [comment]
@javierluraschi thanks for the quick reply.  I've tested a bit more with separate repo and with an explicit, separate pin name.  Workflow with subdirectories worked fine for smaller data files, but I get the identical errors as before when the local file I'm trying to upload is larger than the limit.  Happy to test more on my end.

**Comment by javierluraschi** [comment]
@cboettig could you try using the latest version of `pins` form CRAN?

I'm not being able to reproduce this, this is what I've tried so far:

```r
library(pins)
board_register(board = "github", repo = "javierluraschi/datasets", branch = "rsconf")

writeLines("Hello World", "RStudio/temp/text.file.txt")
pin("RStudio/temp/text.file.txt", board = "github")

# this option forces pins of size bigger than zero to use release files
options(pins.github.release = 0)

pin("RStudio/temp/text.file.txt", name = "test1", board = "github")
pin("RStudio/temp/text.file.txt", name = "test1", description = "2020-02-04 cache of GBIF Taxonomic Names in Darwin Core", board = "github")

pin_get("test1", board = "github")
```
```
[1] "/Users/javierluraschi/Library/Caches/pins/github/test1/text.file.txt"
```

If the file is too big, as in larger than 2GB, GitHub won't be able to store it.

I definitely want to get to the bottom of this, given that the package is quite new, so any additional info would be really useful.

If it's easier, we could chat sometime this week in gitter: https://gitter.im/rstudio/pins

Thanks, @cboettig!

**Comment by cboettig** [comment]
Thanks @javierluraschi ! I can confirm you're examples work perfectly for me, but I still have this fail on files that are in the ~ 20 MB range.  Here's what I hope is a better minimal reproducible example, following on with the same github board after successfully running your examples above:

```
library(nycflights13)
readr::write_tsv(flights, "flights.tsv")
pin("flights.tsv", board = "github")
```

gives me the first of the two errors I mentioned above:
```
Error in curl::form_file(path, type) : is.character(type) is not TRUE
```

and just trying the same `pin` command a second time, I get a the second of the two errors:

```
 Error in github_create_release(board, name) : 
  Failed to create release 'flights-f50502e' for 'flights': Validation Failed
```

Note that `flights.tsv` is about 29.6 MB.  After bz2 compression it is only 4.9 MB and `pins` handles it just fine.

**Comment by cboettig** [comment]
@javierluraschi apologies for not pinging back here sooner, but just wanted to say from my end looks like things are working nicely now, so feel free to close this.   (still interested on your take on the versioning issue though!)

**Comment by javierluraschi** [comment]
Awesome, closing. @kevinykuo also wants versioning support and Hadley pointed out this from the very beginning, so I'm gonna get to work on that. I'm tracking this work with https://github.com/rstudio/pins/issues/178.

**Comment by ries9112** [comment]
I am running into this same issue where I'm creating a pin with a large file using the code:
```R
pin(data, board='github', name='data_reprex')
```

And I am getting the error: 
`Error in curl::form_file(path, type) : is.character(type) is not TRUE`

When I run the exact same code but wrap my data in `head()` there are no errors and the data is successfully pinned, this works fine:
```R
pin(head(data), board='github', name='data_reprex')
```

The data is 1.1Million rows by 83 columns and is ~600MB when written to a .csv and ~70MB according to `object.size()`.

What strikes me as weird about this error is the fact that I have a process that runs on an hourly basis without problems and I just copy/pasted the same code writing the results to a new data source and I'm having this issue, even if the data is smaller in size compared to the process that seems to keep working fine.

Are we sure this issue has to do with file sizes? Here are screenshots from my other process with the same exact data source and more rows working totally fine:
![image](https://user-images.githubusercontent.com/32306488/82274731-2706ca80-993e-11ea-8591-aeafc9666d30.png)

And its recent runs history:
![image](https://user-images.githubusercontent.com/32306488/82274765-3d148b00-993e-11ea-9d4d-e5548d63aafc.png)

The link to the repo and pin from the screenshots: https://github.com/predictcrypto/pins/tree/master/messari

My process has a database connection involved in it that I cannot share, but there is anything that I can provide here to help out, including the data, I'd be more than happy to. I was on the CRAN version of the package originally and I'm having the exact same issue on the development GitHub version of the package.

## Something else I totally do not understand:

If I read the pin that seems to work fine with the following code:
```R
pins::board_register("https://raw.githubusercontent.com/predictcrypto/pins/master/", "messari")`
pins::pin_get("messari", "messari")
```

But somehow it's not able to publish the same data to a new pin:
```R
pin(pins::pin_get("messari", "messari"), board='github', name='messari_reprex')
```
This gives me the error:
`Error in github_create_release(board, name) : 
 Failed to create release 'messari_reprex-e763db2' for 'messari_reprex': Validation Failed`


Sorry to be a bother on a closed issue, I just figured I would just share my experience with this weird error.
