### ISSUE TITLE
Permit multiple attachments to single release in GitHub storage model?

### ISSUE THREAD

**Issue by cboettig** [rstudio/pins#170]
There may be good reasons for `pins` not to do this, so apologies in advance if this doesn't make sense.

I see that `pins` creates a new 'release' for every large file uploaded, while GitHub supports attaching multiple files to a single release (I believe the 2GB limits are only enforced on a per-file basis, not a per-release basis).  

In my existing workflows, I often upload lots of files, and I'm worried about easily bogging down the GitHub API if my repo contains thousands of releases.  

Closely related to this -- most of my uploads are just replacing existing files that I've previously uploaded, and I don't really need to store the full version history.  The GitHub API allows me to overwrite (well, delete and replace) an upload to a released asset.  The current `pins` model with a GitHub backend seems like it is designed to store every single version and never delete something.  I can see the value in that, but it doesn't look like versioning is part of the scope for pins, or that there's any way from within pins to access those old versions, so why not just overwrite files of the same name/description on an existing release instead of creating new releases every time?

**Comment by javierluraschi** [comment]
@cboettig So we do want to support versioning in `pins`, but right now is unsupported or incomplete at best. I think it makes sense to turn off versioning and opt-in for this feature once implemented.

Regarding multiple uploads, it is supported, for instance:

```r
library(pins)
board_register(board = "github", repo = "javierluraschi/datasets", branch = "rsconf")

writeLines("Hello", "hello.txt")
writeLines("World", "world.txt")

options(pins.github.release = 0)

pin(c("hello.txt", "world.txt"), board = "github") %>% print()
```
```
[1] "/Users/javierluraschi/Library/Caches/pins/github/hello/hello.txt"
[2] "/Users/javierluraschi/Library/Caches/pins/github/hello/world.txt"
```

See https://github.com/javierluraschi/datasets/releases/tag/hello-8fecaca, am I missing something on the multiple upload piece?

**Comment by javierluraschi** [comment]
@cboettig let me know if I'm missing something here... seems like this is supported so planning to close this one. Unless you want to upload one file at a time instead of uploading all files together?

**Comment by cboettig** [comment]
Thanks @javierluraschi , (apologies I somehow missed your original reply).  Yeah, I think this is good and can be closed.  

I do think it's a good question as to whether you should be able to upload multiple files to the same release without having to use a vectorized argument to `pins()`, but I think that falls under the broader question of figuring out what it means to be a release.
