### ISSUE TITLE
Support for other git platforms

### ISSUE THREAD

**Issue by blairj09** [rstudio/pins#173]
GitHub is currently a supported pins board. It would be nice of other git platforms were also supported, such as BitBucket and GitLab.

**Comment by javierluraschi** [comment]
Whoa, this got a bunch of thumbs up... I think this is hard since their APIs are completely different :( But I'll investigate a bitt.

**Comment by javierluraschi** [comment]
Looks like migrating from GitHub to GitLab APIs takes effort :( Was hoping the API were mostly compatible but since it's not the case, closing for now. See https://gitlab.com/gitlab-org/gitlab/-/issues/687.
