### ISSUE TITLE
Strings As Factors option for pin_get()

### ISSUE THREAD

**Issue by ries9112** [rstudio/pins#175]
Are there any plans to add functionality similar to utils::read.csv() with the argument stringsAsFactors? Would be nice for pin_get() to have this option to avoid factors when they are not wanted as a data type

**Comment by javierluraschi** [comment]
@ries9112 could you share a simple example? If a data frame is pinned with factors, `pin_get()` will retrieve factors. If a data frame is pinning without factors, `pin_get()` won't retrieve factors either. Thanks!

**Comment by ries9112** [comment]
Thanks for the reply @javierluraschi. I was still figuring things out and I had mistakenly uploaded a pin with a bunch of factors and for some reason I thought that conversion was happening in pin_get(), which is obviously not correct and all that is determined when the pin is uploaded and the issue has nothing to do with the pins package.

I do still want to make one note about this, because I don't think it's super simple to adjust data types in bulk for a dataset when needed in R and I find myself doing hacky workarounds like writing the data to a .csv file and importing it with a function that automatically assigns data types.

For example, if I were to download a pin with 100 variables which contains some strings as factors which I might specifically want to avoid, I would assign the output of pin_get() to an object, then write that object to a .csv file and run utils::read.csv(object, stringsAsFactors=F) to remove the factors.

It makes a ton of sense to stick to the data types as they are described when uploaded as a pin originally, but it could also be useful to have an argument to make some adjustments, for example if you wanted to convert back strings that were recorded as factors, or if you wanted to adjust all of the data types at once, for example if the person uploaded the data as all strings by accident.

I apologize for the issue which has to do with a data issue on my end, closing this now.
