### ISSUE TITLE
Google drive volume?

### ISSUE THREAD

**Issue by kbenoit** [rstudio/pins#184]
I've seen it's possible to register a Google Cloud storage location for hosting a board, but it is also possible to do this in a Google drive using a sharing link?

Thanks!

**Comment by javierluraschi** [comment]
Not currently, but great suggestion. If others are interested, please upvote this feature request. Thanks!

**Comment by kbenoit** [comment]
That would be great. A shared Google Drive volume is super easy to manage (just drag the files into a folder, get a sharing URL), and my organization's GSuite account provides unlimited storage, so it would be a perfect way to host a board.

Thanks for the fast reply!

**Comment by jpmarindiaz** [comment]
+1 very useful. Related to something we discussed at some point about supporting google sheets

**Comment by javierluraschi** [comment]
Tracked in the features board now with https://github.com/rstudio/pins/issues/321, closing this one
