### ISSUE TITLE
Column names modified on RStudio Connect

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#190]
Hi,

Minor issue but might cause some confusion.

I just noticed that if I pin a tibble that contains spaces in the column name, the column name will be changed in the UI but will be correct when I retrieve the tibble from R

     z<-tibble(`With space`=c(1,3))
    pin(z,name="test1",description="tibble with column name space",board = "rsconnect")

Cheers,

Iain

**Comment by javierluraschi** [comment]
Preview does add a `.`... might be an easy fix:

<img width="1439" alt="Screen Shot 2020-12-10 at 11 26 16 AM" src="https://user-images.githubusercontent.com/3478847/101819756-872bac80-3ada-11eb-8dc9-083d8a5591e9.png">
