### ISSUE TITLE
Use data.table::fwrite in pins

### ISSUE THREAD

**Issue by glynnfoster** [rstudio/pins#191]
Our team has preferred the use of `data.table::fwrite` (https://www.rdocumentation.org/packages/data.table/versions/1.12.8/topics/fwrite) to write CSV files, as it tends to be significantly faster. From looking at the code, `pins` looks like it uses `utils::write.csv`

**Comment by javierluraschi** [comment]
We could consider using `data.table` if installed or `readr` as well... that makes sense, I think.

Notice that the CSV is written for interoperability purposes only and can be skipped by creating a pin with `I()`, as in `pin(I(iris))`.

**Comment by glynnfoster** [comment]
Nice tip, thanks @javierluraschi!

**Comment by javierluraschi** [comment]
Right, I think the way to expand this is with a `format = "data.table"` or `format = "parquet"` when registering the board.  See https://github.com/rstudio/pins/issues/73.

Is just that, at this point, this looks like a long-term feature that won't get implemented right away.
