### ISSUE TITLE
Recursive mode for pin_get

### ISSUE THREAD

**Issue by glynnfoster** [rstudio/pins#194]
It would be nice if `pin_get` could support a recursive operation, allowing it to pull down (and cache) several S3 objects within a single transaction. The use case is being able to pull a variety of time stamped CSV data to aggregate into a single dataframe for further analysis.

**Comment by javierluraschi** [comment]
Have you looked into `arrow`? Pins was not designed with high-performance in mind but rather ease-of-use. Marking this as feature request since we can consider making this more efficient, but in the meantime, `arrow` might give you the parallel download from S3 you need.
