### ISSUE TITLE
pin() fails for remote rsconnect board 

### ISSUE THREAD

**Issue by saraemoore** [rstudio/pins#195]
When attempting to knit the RMarkdown document in the example pins project included with RStudio Connect (`stock-import.Rmd`) from RStudio Server Pro, `pin(prices, pin_name, board = "rsconnect")` fails with the following error:
```
Error in pin_download(url, name, board$name, headers = rsconnect_api_auth_headers(board,  :    
  Client error: (404) Not Found. Failed to download remote file: https://subdomain.mycompany.com/rsconnecthttps://subdomain.mycompany.com:443/rsconnect/content/7/data.txt
```
where our RStudio Connect server url is `https://subdomain.mycompany.com/rsconnect` (and our RStudio Server Pro url is `https://subdomain.mycompany.com`, if that matters). Traceback:
```
11: report_error(error)
10: pin_download(url, name, board$name, headers = rsconnect_api_auth_headers(board, 
        path, "GET"), custom_etag = etag)
9: rsconnect_api_download(board, entries[[1]]$name, file.path(remote_path, 
       "data.txt"), etag = etag)
8: board_pin_find.rsconnect(board, text = only_name, name = name)
7: board_pin_find(board, text = only_name, name = name)
6: rsconnect_get_by_name(board, name)
5: board_pin_create.rsconnect(board, store_path, name = name, metadata = metadata, 
       ...)
4: board_pin_create(board, store_path, name = name, metadata = metadata, 
       ...)
3: board_pin_store(board, path, name, description, "table", metadata, 
       ...)
2: pin.data.frame(prices, pin_name, board = "rsconnect")
1: pin(prices, pin_name, board = "rsconnect")
```
The problem appears to be due to the below `gsub()` in `rsconnect_remote_path_from_url()` not behaving as intended because there's a port number in `url` but not in `board$server`, and therefore `board$server` doesn't exactly match the prefix of `url`.
```
url <- gsub(paste0("^.*", board$server), "", url)
```
(In this example, `board$server` is `https://subdomain.mycompany.com/rsconnect` and `url` is `https://subdomain.mycompany.com:443/rsconnect/content/7`.)

I've handled this by changing my `CONNECT_SERVER` environment variable from `"https://subdomain.mycompany.com/rsconnect"` to `"https://subdomain.mycompany.com:443/rsconnect"`. However, I wanted to report this here in case 1) this issue impacts anyone else and/or 2) this could be fixed either via documentation or by aligning the way in which urls are reported (with/without port numbers).

**Comment by javierluraschi** [comment]
@saraemoore thank you so much for reporting this, fix on it's way with https://github.com/rstudio/pins/issues/195. Once merged, you can install fix with:

```
remotes::install_github("rstudio/pins")
```

**Comment by saraemoore** [comment]
No problem -- thanks for the quick fix!

**Comment by saraemoore** [comment]
I was able to try this fix out today. Unfortunately, the issue persists for me, but the workaround (changing `CONNECT_SERVER`) still works. Let me know if you'd like me to test any other fixes.
