### ISSUE TITLE
pin + github_board creates new commit for each file additional file

### ISSUE THREAD

**Issue by cboettig** [rstudio/pins#197]
@javierluraschi pointed out to me in #170 that if you pass a vector of files to `pin()` and have set the threshold size `options(pins.github.release = 0)` to force all uploads to release assets, then they all go on the same release.  

I was thus surprised to see that if I pass a vector of objects to `pin` where I'm using the default size threshhold (and all objects are nice and small) when using a github_board, pin creates a new commit for each object.  It would be nice if possible to have all these files committed in a single commit.  This is probably relevant for versioning (#178) and more immediately, the current setup makes it very very slow for a large vector of small files.  (Though on the flip side, `pin()` with threshold set to 0 just fails when I try to send a lot of objects at once).  

(in other words: whoopsies, did I just make 2913 commits? 🙋‍♂ 😊 )

**Comment by javierluraschi** [comment]
Looks like we should be able to do something like: https://gist.github.com/StephanHoyer/91d8175507fcae8fb31a -- Will fix in next CRAN release.

**Comment by javierluraschi** [comment]
Wait... we are missing to not create multiple large release files... to avoid multiple release files register GitHub without support for versions as follows:

```r
board_register_github(repo = "javierluraschi/datasets", branch = "datasets", versions = FALSE)
```

Obviously, versioning can't be turned off in GitHub commits (I guess we could modify the history, but anyways)... but what this does is to avoid creating versioned releases. I'll resolve this with https://github.com/rstudio/pins/issues/91
