### ISSUE TITLE
data.txt file not placed in the right path for github board or with wrong relative paths for pins

### ISSUE THREAD

**Issue by jpmarindiaz** [rstudio/pins#199]
When using the path parameter for github boards (I used a data folder), the data.txt file is created inside the `data` folder. Which is fine, the problem is with paths inside the data.txt file that are not relative to the `data` folder as I expected.
See repo in data folder [here](https://github.com/jpmarindiaz/opendata/tree/119adb8474a782a5b4d05a918346b5c2e4fe573f/data)
These are the [contents](https://github.com/jpmarindiaz/opendata/blob/119adb8474a782a5b4d05a918346b5c2e4fe573f/data/data.txt) of the `data/data.txt` file

I believe one `data.txt` file should be placed in the root of the repo, but also there should be a `data/data.txt` file with relative paths to all pins inside the `data` folder.

**Comment by javierluraschi** [comment]
Hoping this is easy to investigate and fix...
