### ISSUE TITLE
Add path parameter to s3 boards

### ISSUE THREAD

**Issue by jpmarindiaz** [rstudio/pins#200]
It would be really useful to register s3 boards not only in the root of the bucket but also in a given `path` in the same way github boards work now.
A use case would be a static site that has a `raw-data` folder and an `analysis` folder to share different types of data and results. There would be `data.txt` in the root of the bucket as well as in the `bucket/raw-data` and `bucket/analysis` folder. 
Same with github boards #199 

```
  board_register("s3",
                 name = name,
                 bucket = bucket,

                 path = path,

                 key = key,
                 secret = secret,
                 cache = cache,
                 ...)
```

**Comment by javierluraschi** [comment]
Hoping this is easy to investigate and fix...
