### ISSUE TITLE
pin(a_pin) creates "a-pin" not "a_pin"

### ISSUE THREAD

**Issue by maurolepore** [rstudio/pins#213]
`pin(a_pin, name =  "a_pin")` works as I expected but `pin(a_pin)` creates "a-pin" not  "a_pin". Is this intentional?

``` r
a_pin <- 1
pins::pin(a_pin, name = "a_pin")
pins::pin(a_pin)

cache <- pins::board_cache_path()
fs::path_file(
  fs::dir_ls(cache, recurse = TRUE, regexp = "a.pin", type = "directory")
)
#> [1] "a-pin" "a_pin"
```

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by javierluraschi** [comment]
Yeah, intentional, when the name is not specified, we convert invalid characters to `-`. This is for convenience only, if you want a explicit name, you need the `name` parameter as you are suggesting.
