### ISSUE TITLE
Add API Key Reminder on RStudio Connect

### ISSUE THREAD

**Issue by akgold** [rstudio/pins#214]
When a pin is deployed to RStudio Connect, it (very helpfully) renders the download text on the page. If the pin is being called from content deployed on Connect, an API key needs to be provided in the `board_register` call. It would be even more helpful if this were conveyed to users on the page on RStudio Connect.

**Comment by javierluraschi** [comment]
`from content deployed on Connect` is a quite advanced use case... I think we need to optimize for people copy-pasting code to their RStudio console. Not heavily inclined to this, but I'd argue is better to help new users and advanced users can figure out the extra parameters.
