### ISSUE TITLE
Fn for auth auto-setup with RSC

### ISSUE THREAD

**Issue by akgold** [rstudio/pins#215]
It would be super cool to have an interactive function like `pins::setup_rsc_auth` that would create an API key on RStudio Connect, add it to an .Renviron, and then provide a code snippet to use to register the board. We see many users run into confusion about having to provide an API key when deploying when they haven't needed one while developing.

H/T to @slopp for the idea.

**Comment by slopp** [comment]
I think all this function would need to do is a clever use of `browseURL` and then navigating the clipboard, similar to the gargle helpers for OAuth. It wouldn't need to actually do all the work of interacting with the RSC Server API. 

The challenge users face is knowing how to get the right code snippet with an API Key for connecting reliably to their board in a programmatic-friendly way.

**Comment by javierluraschi** [comment]
Right, I think this is out of the scope of `pins` for now. But never say never! Closing for now.
