### ISSUE TITLE
Add support for Put Blocks in Azure

### ISSUE THREAD

**Issue by dareneiri** [rstudio/pins#218]
For files larger than 64MB, Pins is unable to use Azure as a Board due to Blob limitations for the current version being used: 
https://github.com/rstudio/pins/blob/master/R/board_azure.R#L3

https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob

> The maximum size for a block blob created via Put Blob is 256 MB for version 2016-05-31 and later, and 64 MB for older versions. If your blob is larger than 256 MB for version 2016-05-31 and later, or 64 MB for older versions, you must upload it as a set of blocks. For more information, see the Put Block and Put Block Listoperations. It's not necessary to also call Put Blob if you upload the blob as a set of blocks.
> 
> If you attempt to upload a block blob that is larger than 256 MB for version 2016-05-31 and later, and 64 MB for older versions, or a page blob larger than 8 TB, the service returns status code 413 (Request Entity Too Large). The Blob service also returns additional information about the error in the response, including the maximum blob size permitted in bytes.
> 

Using 2019-02-02 could resolve this issue for files smaller than 256 MB, but it would likely be more proper to add functionality to support Put Block for larger files.

**Comment by javierluraschi** [comment]
Not likely to be able to address this anytime soon, workaround is to split data into multiple pins for Azure. We would really appreciate a PR here if the community has time to help enable large uploads to Azure.
