### ISSUE TITLE
pins::pin() fails silently when content with same name exists in RSC

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/pins#226]
When a piece of context exists in RStudio Connect (RSC) and you pin an object with the same name you will encounter no errors until you try and retrieve the pin. It would be nice to be given a warning when you try and make a pin with the same name as a piece of content in RSC.

v

**Comment by ASBecker** [comment]
Another option would be to add a parameter `overwrite` to the function, where the user can specify whether he wants `pin` to throw a warning/error or silently overwrite existing pins (from the definition of what a 'pin' is I would think the default behaviour should be `TRUE`)

**Comment by javierluraschi** [comment]
I believe this has been fixed or at least, improved.

**Comment by JosiahParry** [comment]
thanks javier! :)
