### ISSUE TITLE
Better documentation on `board` argument

### ISSUE THREAD

**Issue by kmasiello** [rstudio/pins#228]
It would be helpful to have better documentation in the `board_register` and `pin` help files to specify that the `board` argument has specific expected values: rsconnect, local, github, kaggle, or datatxt.

**Comment by javierluraschi** [comment]
The `board` parameter is the name of the registered board. So it extends beyond the mentioned ones, you can also do:

```
board_register_s3(name = "otherS3", bucket = "", key = "")
```

and then run:

```
pin(iris, board = "otherS3")
```
