### ISSUE TITLE
Possible problem with s3 buckets that contain dots in their name

### ISSUE THREAD

**Issue by jpmarindiaz** [rstudio/pins#229]
There might be some unexpected scaping of dots `.` in bucket names.

I am able to run this:
```
 board_register_s3(bucket = "xxx.yyy.zzz")
 pin(mtcars, board = "xxx.yyy.zzz")
```
And I get this error:
```
Error in pin_download(path, name, board$name, extract = identical(extract,  : 
  Client error: (404) Not Found. Failed to download remote file: http://xxx.yyy.zzz.s3.amazonaws.com/mtcars
```
Funny thing is that the file gets uploaded correctly. But then `pin`fails when it tries to download the uploaded pin. Running again with `options(pins.verbose = TRUE)`. The console outputs:
```
Storing mtcars into board xxx.yyy.zzz with type table
Checking 'change_age' header (time, change age, max age): 1590276706.44661, 1590276706.44656, 0
Checking 'etag' (old, new): , 
Downloading http://xxx.yyy.zzz.s3.amazonaws.com/mtcars/data.txt to /var/folders/2m/5p4nlx0d2_z_f8hsgvbwmpqc0000gn/T//RtmpeIjUCC/filef095a0c8833/data.txt
No encoding supplied: defaulting to UTF-8.
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchBucket</Code>
  <Message>The specified bucket does not exist</Message>
  <BucketName>xxx</BucketName>
  <RequestId>3C88ABA1354172CE</RequestId>
  <HostId>U9BamOkMZbT8/swohTQnl+uycdfY1clGoy1QMK/WY26pNghp1+ccpQ70lCMbiQjisH31OenBVVc=</HostId>
</Error>
```
Note that `<BucketName>xxx</BucketName>` is only showing the first part `xxx` of the bucket name... the part before the first dot.

Because of this even when the file gets uploaded and pinned(*), it does not retrieve it back. I tried to look at the `pins` source but I still don't understand it well to propose a solution.

(*) A quick note, when the download fails, I noticed that the `data.txt` is replaced in full and not appended to the previous one, losing the info of all pins in the bucket. Is this another issue? I believe the `data.txt` pin catalog should be updated right after successful upload and independent of the success of pin retrieval.

I also believe this hast to do with the latests comments in https://github.com/rstudio/pins/issues/188

**Comment by javierluraschi** [comment]
@jpmarindiaz can you verify this one was also fixed by https://github.com/rstudio/pins/issues/237? You'll need to install with `remotes::install_github("rstudio/pins")`, thanks!

**Comment by jpmarindiaz** [comment]
Yes, it works now. Thanks
