### ISSUE TITLE
S3 bucket permissions

### ISSUE THREAD

**Issue by Keceltes** [rstudio/pins#230]
Hi all,
I’d like to try out s3 boards and am getting permission issues, I don’t want to make things completely public and suspect there’s probably some middle ground for s3 bucket policy but I don’t see any documentation on what that middle ground is.  Anyone mind pointing me towards the right place?
 
```r
library(pins)
 
board_register_s3(bucket = "kevin-test-redda",
                  key = "",
                  secret = "")
 
x <- 3
 
pin(x, description = "The iris data set", board = "s3")
```
```
# Error in datatxt_upload_files(board = board, name = name, files = upload_files,  : 
# Failed to upload 'data.rds' to 'http://kevin-test-redda.s3.amazonaws.com/x/data.rds'. Error: <?xml version="1.0" encoding="UTF-8"?>
# <Error>
# <Code>AccessDenied</Code>
# <Message>Access Denied</Message>
# <RequestId>9CD45D9AC3633745</RequestId>
# <HostId>TvFXgBslAWc1qLNHhfN8BbXKhOEF7W6ZpYwwZ1Nkf7NfXSXx5Jsy2eTNvS60es2jeQhPrgpLx+I=</HostId>
# </Error>
```

```r
pin_get("test.txt", board = "s3") # wasn't expecting to work cause file doesn't exist, but curious what error message would be
```
```
# Error in pin_download(path, name, board$name, extract = identical(extract,  : 
# Client error: (403) Forbidden. Failed to download remote file: http://kevin-test-redda.s3.amazonaws.com/test.txt
```

**Comment by javierluraschi** [comment]
The S3 key/secret token that you create must have the appropriate permissions to store S3 objects and retrieve them. You don't need to make any pin public if you prefer to keep them private, but you do need to configure permissions for that user (key/secret) in that particular bucket.

The `pins` package does not provide any functionality to help you manage permission, it simply uses the user (key/secret) that is provided when the board is registered and attempts to upload/download files.

**Comment by jpmarindiaz** [comment]
Hi
You can go about it in two ways, either by creating a bucket policy, or by creating a policy for a user. If you use IAM please check the policy generator, then you can create a user and attach a policy to the user to be able to list all your buckets and then to perform specific actions in your bucket.
Something along these lines will get you there. You would have to tweak the policy for your specific needs, so check the documentation on Amazon policies.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Sid": "AllObjectActions",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::mybucket*",
                "arn:aws:s3::::::mybucket*/*"
            ]
        }
    ]
}
```

**Comment by Keceltes** [comment]
I am able to upload directly with the access/secret key via aws cli, so if I understand the above correctly it should be working.  I also specify sse encryption, default to AES256.  Is there a way to specify that in the pin() command as an argument?  I don't see it in the documentation.

**Comment by Keceltes** [comment]
All,
My colleague was able to figure out there was an issue with board_register_s3 and the https/http protocol.  He wrote a customer wrapper around board_register to convert the protocol and we were able to pin and get pins.  I will ask him to provide more information (Afshin).

**Comment by afshinmhCLG** [comment]
As @Keceltes  mentioned, I was observing the same issue. Tracing the issue, it boiled down to what seems to be hard-coding of "http" call vs "https" within `board_initialize.s3`.  Specifically, writing a wrapper that simply
replaces
`s3_url <- paste0("http://", board$bucket, ".", host)`
with 
`s3_url <- paste0("https://", board$bucket, ".", host)`

did the trick on our end.

**Comment by javierluraschi** [comment]
`https` is now hardcoded, so I believe this is now fixed? Otherwise, feel free to open a new issue, thanks!

**Comment by afshinmhCLG** [comment]
I tested this on my end based on the latest version and all works well now. Thanks @javierluraschi!!
