### ISSUE TITLE
On some S3 regions, pin() gets "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256"

### ISSUE THREAD

**Issue by dgrtwo** [rstudio/pins#233]
When saving data to S3, I found that whether R can save to a bucket depends on what region the bucket is in, and it fails in "US East (Ohio)". I think this is because it uses Signature Version 2.

When I tried writing to two buckets, one in `US West (Oregon)` and one in `US East (Ohio)`, the Oregon upload works perfectly and the East fails with the below error. My key has permission to read/write both buckets, and identical settings (e.g. neither has encryption enabled).

```
 Error in datatxt_upload_files(board = board, name = name, files = upload_files,  : 
  Failed to upload 'data.csv' to 'http://MYBUCKET.s3.amazonaws.com/test_mtcars/data.csv'. Error: <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>InvalidRequest</Code>
  <Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
  <RequestId>REQUESTID</RequestId>
  <HostId>HOSTID</HostId>
</Error>
```

From [this guide in the AWS documentation](https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html), it looks like only 8 regions support Signature Version 2, and US East (Ohio) isn't one of them.

**Comment by ZellW** [comment]
Did not know how to resolve this problem until I saw this.

**Comment by javierluraschi** [comment]
We need to update S3 signatures, this is starting to become urgent...

**Comment by drusttaib** [comment]
Hey man, did you find a way to solve this? I want to use US-EAST-2

**Comment by javierluraschi** [comment]
@drusttaib not yet but planning to work on this next week... should have a fix for this soon.

**Comment by drusttaib** [comment]
> @drusttaib not yet but planning to work on this next week... should have a fix for this soon.

Hey man I fixed the issue by adding
This line in web.config file![20201212_000306.jpg](https://user-images.githubusercontent.com/28954289/101954510-48e2da00-3c0d-11eb-9e6d-fa9a0b7917fe.jpg)

**Comment by drusttaib** [comment]
> When saving data to S3, I found that whether R can save to a bucket depends on what region the bucket is in, and it fails in "US East (Ohio)". I think this is because it uses Signature Version 2.
> 
> When I tried writing to two buckets, one in `US West (Oregon)` and one in `US East (Ohio)`, the Oregon upload works perfectly and the East fails with the below error. My key has permission to read/write both buckets, and identical settings (e.g. neither has encryption enabled).
> 
> ```
>  Error in datatxt_upload_files(board = board, name = name, files = upload_files,  : 
>   Failed to upload 'data.csv' to 'http://MYBUCKET.s3.amazonaws.com/test_mtcars/data.csv'. Error: <?xml version="1.0" encoding="UTF-8"?>
> <Error>
>   <Code>InvalidRequest</Code>
>   <Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
>   <RequestId>REQUESTID</RequestId>
>   <HostId>HOSTID</HostId>
> </Error>
> ```
> 
> From [this guide in the AWS documentation](https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html), it looks like only 8 regions support Signature Version 2, and US East (Ohio) isn't one of them.

![20201212_000306.jpg](https://user-images.githubusercontent.com/28954289/101954589-6748d580-3c0d-11eb-9934-f33aacd592b4.jpg)  add this line to your web.config file

**Comment by javierluraschi** [comment]
Please see https://github.com/rstudio/pins/issues/304 which added support for AWS S3 V4 signatures. To activate AWS S3 V4 signatures, please include the `region` parameter when the S3 board is registered.

**Comment by STO123456789** [comment]
I’m turning this in to my Attorney as well charges are being filled

**Comment by SpaceMonkey-TheCoder** [comment]
For NodeJS AWS SDK, add `signatureVersion: 'v4'` in the config. For example:

`const S3 = new AWS.S3({
  accessKeyId: awsConfig.keyId,
  secretAccessKey: awsConfig.secret,
  signatureVersion: 'v4'
});`
