### ISSUE TITLE
Registered board (network drive) disappears with new R session 

### ISSUE THREAD

**Issue by leungi** [rstudio/pins#240]
#### Steps performed:
1. In brand new R session, register board
```r
board_register(board = "local", name = "DMA", cache = "/ADAM/", versions = TRUE)
```

- here, `/ADAM/` is a network drive
- this drive is accessible by Windows and Linux machines, and the intention is use `pins` to get/save data

2. `board_list()` confirms registration OK
```r
board_list()
#> [1] "DMA"      "local"    "packages"
```

3. `pin_*()` works as designed (for this session)
```r
pin_find("mtcars", "DMA")
#> A tibble: 1 x 4
#>  name   description        type  board
#>  <chr>  <chr>              <chr> <chr>
#> 1 mtcars the mtcars dataset table DMA

pin_get("mtcars", "DMA")
#> A tibble: 32 x 11
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#> 2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#> 3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
```

4. Restart R session, and the `DMA` board is missing; re-registration required.
```r
board_list()
#> [1] "local"    "packages"

pins::pin_find("hopspp", "DMA")
#> Error in board_get(board_name) :
#>   Board 'DMA' not a board, available boards: local, packages
```

#### Comments
From the [docs](https://pins.rstudio.com/reference/board_register.html), this behaviour is expected when using a temp folder, but I don't expect it for persistent network drive.

#### Session Info
```r
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.3 (Maipo)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] pins_0.4.1

loaded via a namespace (and not attached):
[1] compiler_3.6.0  backports_1.1.4 magrittr_1.5
```

**Comment by javierluraschi** [comment]
This is by-design, pins does not remember connections between R sessions.

To make this easier, the RStudio Connection's Pane does remember the previous `board_register()` call, so you should be able to reconnect to this board without having to remember the connection parameters.

**Comment by leungi** [comment]
Noted; thanks @javierluraschi .

I tried using options `pins.board`, but...😅

Thanks again for the work; I'm also reading your book _Mastering Spark with R_ 👏🙏
