### ISSUE TITLE
Support for `max_versions` when versioning

### ISSUE THREAD

**Issue by dareneiri** [rstudio/pins#242]
It would be nice to have support to add `max_versions` when using `pin()` as reasons stated in #178 

For R Connect, the only way to manage the versions is to delete through the web interface. 

Thanks!!

**Comment by scubastevew** [comment]
Pro customer has requested a feature like this: ticket ID 50797

**Comment by kmasiello** [comment]
Another pro customer request for this feature.  +1

**Comment by dareneiri** [comment]
FWIW I am also a Pro customer

**Comment by javierluraschi** [comment]
Looks like an feature in RStudio Connect was more appropriate, closing.
