### ISSUE TITLE
When pinning to R Connect, have ability to set collaborator

### ISSUE THREAD

**Issue by dareneiri** [rstudio/pins#243]
When you pin to R Connect, by default the only collaborator is whoever publishes. 

It would be nice to define a list of collaborators when using `pin()`

**Comment by JosiahParry** [comment]
This is the default behavior of any content that is deployed to Connect (RSC). The package [`rsconnect`](https://github.com/rstudio/rsconnect) is used for deploying content to RSC, ShinyApps.io or elsewhere. This would require the functionality to be added into the `rsconnect` package or the Connect API. Today there is no ability, as I understand the product, to determine viewers or collaborates without entering the Connect UI. 

I'm currently dealing with the same minor irritation :P 

I'll pass this on as a feature request!

**Comment by javierluraschi** [comment]
Reasonable feature request; however, workaround is to change this from the RStudio Connect UI, not likely to be implemented in the short-term, so closing for now.
