### ISSUE TITLE
Cannot pin scalar character

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/pins#247]
It is not possible to pin a scalar character. I thought perhaps I could return the file name but it returns the full file path. 

I understand that when a scalar character is provided {pins} thinks its a file path. But this means that I can't pin all R objects unfortunately. 

``` r

scalar_char <- "this is a scalar"

pins::pin(scalar_char, "scalar")
#> Warning in file.copy(single_path, store_path, recursive = TRUE): problem reading
#> directory ./this is a scalar: No such file or directory

pins::pin_get("scalar")
#> character(0)
pins::pin_get("scalar", files = TRUE)
#> [1] "/Users/josiah/Library/Caches/pins/local/scalar/this is a scalar"
```

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The alternative is to wrap the scalar in a list and then pin it.

``` r

scalar_char <- list("this is a scalar")

pins::pin(scalar_char, "scalar-in-list")

pins::pin_get("scalar-in-list")
#> [[1]]
#> [1] "this is a scalar"
```

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by javierluraschi** [comment]
A workaround is to use `I()`:

```
pins::pin(I("Hello"), "character")
```

**Comment by JosiahParry** [comment]
Oh Interesting! Good to know. Thanks!
