### ISSUE TITLE
Feature request: pin_exists()

### ISSUE THREAD

**Issue by ASBecker** [rstudio/pins#251]
I've written what is essentially a small wrapper for `pin_find %>% nrow` but found it useful for if - else statements (e.g. when adding rows to existing pin via `pin_get %>% bind_rows %>% pin` versus new `pin`). I'd find it useful if something like this was available as an exported function from `pins`.

```
pin_exists <- function(name, board = "local") {
  output <- ifelse(nrow(pin_find(name = name, board = board))==0, FALSE, TRUE)
}
```

**Comment by javierluraschi** [comment]
I think we are likely to take a PR with this code, but probably not likely to work on this in the short-term, so closing.
