### ISSUE TITLE
trying to put a pin into S3 error

### ISSUE THREAD

**Issue by grobins** [rstudio/pins#267]
I'm trying to run 

```
pin(mtcars, name="mtcars", description = "The mtcards data set", board = "s3")
```
and get this error.

Error in curl::curl_fetch_memory(url, handle = handle) : 
  necessary data rewind wasn't possible

I'm able to register the s3 bucket as a board, and I can connect to it (it's empty as I can't put anything in there).

**Comment by javierluraschi** [comment]
@grobins usually this happens when the S3 bucket is new and it's still replicating in DNS. I usually have to give it an hour before using a new S3 bucket with pins.

**Comment by grobins** [comment]
Thanks.  that worked.
