### ISSUE TITLE
S3 board error

### ISSUE THREAD

**Issue by cbessey** [rstudio/pins#268]
### Failed to retrieve latest data.txt file, the pin was partially removed

I keep getting this error when attempting to pin to an S3 board.  How do I fix this?

**Comment by javierluraschi** [comment]
There was indeed a regression which affects the last version of pins 0.4.2, a fix is already available, please install with:

```
remotes::install_github("rstudio/pin")
```

A patch is also being applied to CRAN and should be available in the next couple days under pins 0.4.3, thank you for reporting this, @cbessey!
