### ISSUE TITLE
Trying to pin a named vector gives file.copy errors?

### ISSUE THREAD

**Issue by genobobeno** [rstudio/pins#272]
If pins doesn't save R objects, in general, I'd love for the documentation to say what kinds of objects cannot be pinned. I tried pinning a named vector and got the following errors and an empty data object being interpreted as a data.frame:

> pin(x=MartNames,description = "Selectable Marts in MartGuide",board = "rsconnect")
Warning messages:
1: In file.copy(single_path, store_path, recursive = TRUE) :
  problem reading directory ./Auto Mart: No such file or directory
2: In file.copy(single_path, store_path, recursive = TRUE) :
  problem reading directory ./Mortgage Mart: No such file or directory
3: In file.copy(single_path, store_path, recursive = TRUE) :
  problem reading directory ./Daily Triggers: No such file or directory
4: In file.copy(single_path, store_path, recursive = TRUE) :
  problem reading directory ./Demographic: No such file or directory
5: In file.copy(single_path, store_path, recursive = TRUE) :
  problem reading directory ./Homeowner: No such file or directory
6: In file.copy(single_path, store_path, recursive = TRUE) :
  problem reading directory ./FMCG Business Mart: No such file or directory
7: In file.copy(single_path, store_path, recursive = TRUE) :
  problem reading directory ./Premover Mart: No such file or directory

**Comment by javierluraschi** [comment]
Try doing,

```r
pin(x = I(MartNames), description = "Selectable Marts in MartGuide",board = "rsconnect")
```

The `I()` directive signals `pins` to pin the object as-it-is.
