### ISSUE TITLE
Avoid copying files to temp folder when using pin()

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/pins#273]
When uploading really large files, would be more efficient to avoid copying the file before uploading, see: https://github.com/rstudio/pins/blob/380caa926558a73e95a7903f0747ad31c4b0a05b/R/pin_extensions.R#L71

Hit this while attempting to upload ImageNet to GCloud:

```r
library(pins)
pin_get("c/imagenet-object-localization-challenge", board = "kaggle") %>%
  pin("imagenet", board = "gcloud")

```

**Comment by javierluraschi** [comment]
This one is unfortunately not that easy to implement since the extensions API assumes a folder is provided for upload and various helper functions, in versioning, etc, also assume a blank folder is created, same for creating bundles, etc.

One option would be to use symlinks in Linux systems for large files.

**Comment by sjimellor-jr** [comment]
I think there may be an issue with version 0.4.4 on Windows and large pins. A colleague gets an error:

Error: [EINVAL] Failed to link 'path/to/large/file.csv' to 'C:/Users/username/temp/path/to/large.csv': invalid argument

I am not personally on a system that I can reproduce with but this appears to be related to the recent merge using sym-links for large files.

**Comment by javierluraschi** [comment]
Thanks, this fix/improvement was disabled in Windows.
