### ISSUE TITLE
Support for `pin(format = "format")` and parquet

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/pins#284]
Would be nice to support `write_something`, `read_something` functions, like `read_json`, `write_json`, etc. through a `format = "something"` argument. This could be quite useful to use parquet and similar formats. Pins would not depend on those packages, but rather would error out in `pin_get()` if the package that implements the reader/writer is not installed.

**Comment by jthomasmock** [comment]
An additional consideration this is a bit more complex is support for either `arrow` partitioning a la: 
[Link](ds <- open_dataset("nyc-taxi", partitioning = c("year", "month"))) to example from `arrow`.
```
ds <- arrow::open_dataset("nyc-taxi", partitioning = c("year", "month"))
```

This would require sub-folders within a `pin`.

**Comment by javierluraschi** [comment]
Definitely useful, but not likely happen in the short-term.
