### ISSUE TITLE
github releases delete does not remove tags

### ISSUE THREAD

**Issue by 1beb** [rstudio/pins#285]
Tags are left over when deleting a github release

**Comment by javierluraschi** [comment]
We probably need to trigger `DELETE` here, should be an easy fix:

https://github.com/rstudio/pins/blob/master/R/board_github.R#L140-L149

**Comment by javierluraschi** [comment]
Notice that releases will only get delete if the GitHub board is registered with `versions = FALSE`. Otherwise, each change to the pin will generate a new release file to ensure that we can restore previous versions of the pin.
