### ISSUE TITLE
Can't update pins in Rstudio Connect

### ISSUE THREAD

**Issue by TjebsC** [rstudio/pins#289]
When trying to pin an object to Rstudio Connect I get this error:

`Error in board_pin_create.rsconnect(board, store_path, name = name, metadata = metadata, : Failed to create pin: Operation failed with status 409: 26Operation failed with status 409: An object with that name already exists.Operation failed with status 409: NULL`

Running the current Pins version from CRAN 0.4.3. 

A workaround is using pin_remove() before pinning it. Although I then get a warning if it can't find the pin and my whole ETL-process stops. The Pin is also not available on Rstudio Connect and leads me to make a new name for the pin and change that in my code that gets the pin as well. Worth mentioning that I run R 3.4.4. due to some legacy in the corporation

**Comment by javierluraschi** [comment]
@TjebsC would you mind trying with the devel version of `pins` by running:

```
remotes::install_github("rstudio/pins")
```

and then restarting your R session?

**Comment by TjebsC** [comment]
Thank you for your reply @javierluraschi!

I have updated to the dev.version: 0.4.3.9005 - but due to being on an incredibly old setup and having some dependencies on older packages I did not install the newest version of suggests. The current versions are listed here:
                       
 4: backports (1.1.4  -> 1.1.9 ) [CRAN]
 5: digest    (0.6.20 -> 0.6.25) [CRAN]
 6: fs        (1.4.0  -> 1.5.0 ) [CRAN]
 7: httr      (1.4.1  -> 1.4.2 ) [CRAN]
 8: jsonlite  (1.6    -> 1.7.0 ) [CRAN]
 9: mime      (0.7    -> 0.9   ) [CRAN]
10: openssl   (1.4.1  -> 1.4.2 ) [CRAN]
11: withr     (2.1.2  -> 2.2.0 ) [CRAN]
12: yaml      (2.2.0  -> 2.2.1 ) [CRAN]
13: zip       (2.0.4  -> 2.1.1 ) [CRAN]
14: curl      (4.0    -> 4.3   ) [CRAN]
15: R6        (2.4.0  -> 2.4.1 ) [CRAN]
16: sys       (3.2    -> 3.4   ) [CRAN]

I am still able to pin and retrieve it afterwards but whenever I try to pin it again, I get the following error: 
`Error in board_pin_create.rsconnect(board, store_path, name = name, metadata = metadata,  : 
  Failed to create pin: Operation failed with status 404: 404 page not found`

The code ran for this example:
`board_register_rsconnect(key = "key", server = "rsc.server, account = "account")`

`pin(iris, name = "Test_something2", description = "test, the iris data set", board = "rsconnect")`
`pin_get("Test_something2", board = "rsconnect")`


Again, on the first run this works fine, but the next time around I get the error above. I'm using pins as part of an ETL process through markdown. Should I then use the argument `output_files = TRUE` inside the board_register-function?

Thank you for your help!

**Comment by jhhughes256** [comment]
@TjebsC @javierluraschi I think I'm experiencing the same issue when trying to pin an object from an RMarkdown report deployed to RStudio Connect. 

My set up is similar to @TjebsC in that I register the board using `board_register_rsconnect` (providing key, server and account) before trying to using `pin`. This issue occurs for me even after updating to the development version of `pins` (and updating all dependencies) using the code provided by @javierluraschi 

When attempting to pin to a new name I get the following error:

```
[Connect] 2020/10/21 10:00:36.639703093 Error in curl::curl_fetch_memory(url, handle = handle) : 
[Connect] 2020/10/21 10:00:36.639713093   necessary data rewind wasn't possible
[Connect] 2020/10/21 10:00:36.639736704 Calls: local ... request_fetch -> request_fetch.write_memory -> <Anonymous>
```

However, when attempting to pin to that same name again I get the error mentioned by @TjebsC 

```
[Connect] 2020/10/21 10:03:17.028737412 Error in board_pin_create.rsconnect(board, store_path, name = name, metadata = metadata,  : 
[Connect] 2020/10/21 10:03:17.028746376   Failed to create pin: Operation failed with status 409: 26Operation failed with status 409: An object with that name already exists.Operation failed with status 409: NULL
[Connect] 2020/10/21 10:03:17.028779060 Calls: local ... board_pin_store -> board_pin_create -> board_pin_create.rsconnect
```

When looking on RStudio Connect Content Pane after running the first time I find an unpublished content entry with the same name as my pin when I specifically choose "Owner: Yours" in the Options.

![image](https://user-images.githubusercontent.com/20290321/96731269-104d1f80-1385-11eb-9f79-9e64b0d9d00b.png)

When opening the content url I see the following:

![image](https://user-images.githubusercontent.com/20290321/96731554-5f935000-1385-11eb-9d5e-1f1b55908e35.png)

I've provided the package versions according to running `sessionInfo()` below if that helps at all...

```
R version 3.6.2 (2019-12-12)
attached base packages: 
[1] stats     graphics  grDevices utils     datasets  methods   base       
other attached packages: 
[1] pins_0.4.3.9005 purrr_0.3.3     stringr_1.4.0   dplyr_0.8.4     tidyr_1.0.2     rjson_0.2.20    rvest_0.3.5     httr_1.4.2      
[9] xml2_1.2.2       
loaded via a namespace (and not attached):  
[1] rstan_2.19.3       tidyselect_1.0.0   xfun_0.12          remotes_2.1.1      vctrs_0.2.3        colorspace_1.4-1   htmltools_0.4.0     
[8] stats4_3.6.2       loo_2.2.0          yaml_2.2.1         rlang_0.4.5        pkgbuild_1.0.6     pillar_1.4.3       withr_2.3.0        
[15] glue_1.3.2         rappdirs_0.3.1     matrixStats_0.55.0 lifecycle_0.2.0    munsell_0.5.0      gtable_0.3.0       evaluate_0.14      
[22] inline_0.3.15      knitr_1.28         callr_3.4.3        ps_1.3.2           curl_4.3           parallel_3.6.2     fansi_0.4.1        
[29] Rcpp_1.0.3         openssl_1.4.1      scales_1.1.0       backports_1.1.5    filelock_1.0.2     StanHeaders_2.19.2 jsonlite_1.6.1     
[36] gridExtra_2.3      ggplot2_3.3.0      askpass_1.1        digest_0.6.25      stringi_1.4.6      processx_3.4.2     rprojroot_1.3-2    
[43] grid_3.6.2         cli_2.0.2          tools_3.6.2        magrittr_1.5       tibble_2.1.3       crayon_1.3.4       pkgconfig_2.0.3    
[50] rsconnect_0.8.16   prettyunits_1.1.1  assertthat_0.2.1   rmarkdown_2.1      rstudioapi_0.11    R6_2.4.1           compiler_3.6.2
```

Thanks for looking at this!

**Comment by jhhughes256** [comment]
@TjebsC I've ended up using RMarkdown Output Files using the `rmd_output_metadata` YAML header to achieve what I was trying to achieve with `pins`. Providing a link in case it helps you out for your use case. [Link.](https://docs.rstudio.com/connect/1.7.4/user/r-markdown.html#r-markdown-output-files)

**Comment by TjebsC** [comment]
Thank you for your reply, @jhhughes256!

That should work, although pins would have been the ideal solution, as my pre-processing stage only adds data and never deletes. This is a great workaround!

**Comment by javierluraschi** [comment]
Last release to CRAN pushed fixes to properly overwrite existing pins in RStudio Connect, specifically addressing the `An object with that name already exists.` issue. Should be fixed now but please open new GitHub issue if issue still persists.

**Comment by TjebsC** [comment]
Hi again - 

Im still having the same problem as stated in my first post with pins version 0.4.5:
`Error in board_pin_create.rsconnect(board, store_path, name = name, metadata = metadata, : Failed to create pin: Operation failed with status 409: 26Operation failed with status 409: An object with that name already exists.Operation failed with status 409: NULL`

**Comment by jhhughes256** [comment]
Hi TjebsC, 

I don't know if our problems were the same but I managed to get my errors to resolve.

My issue was related to being able to connect to the RSC server successfully using a shortened server name "rsc.mycompany.com" when using `board_register_rsconnect`. When I tried to create a pin it would fail, and then subsequent attempts would provide the error you've shown.

I solved this by connecting to the server using the full server name when using `board_register_rsconnect` specifying the use of HTTPS, i.e. "https://rsc.mycompany.com". It might be that it was assuming HTTP? I don't know enough to be sure.

I hope that this is your problem too for an easy fix, but if not I think it may be worth reopening this.

Good luck! 🙂

**Comment by TjebsC** [comment]
> I solved this by connecting to the server using the full server name when using `board_register_rsconnect` specifying the use of HTTPS, i.e. "https://rsc.mycompany.com". It might be that it was assuming HTTP? I don't know enough to be sure.

Thank you again for great insight, @jhhughes256 . I'm already using HTTPS in `board_register_rsconnect`. 

The reason I'm revisiting this is because a pin suddenly disappeared from the board and the shiny-app that used the pin and was in production crashed. When trying to recreate it I get the error above

> `Error in board_pin_create.rsconnect(board, store_path, name = name, metadata = metadata, : Failed to create pin: Operation failed with status 409: 26Operation failed with status 409: An object with that name already exists.Operation failed with status 409: NULL`

The workaround for me when this happens is to just rename the pin, and update all references. Although this is a sub-optimal solution and I'll never know when the next crash comes.
