### ISSUE TITLE
Roadmap available?

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#29]
This is a very exciting package! It will enable FAIR data sets in an organization. Do you have a roadmap that you could share? I am wondering specifically about versioning, storing additional metadata with a resource, and how best to administer a board on RStudio connect

**Comment by javierluraschi** [comment]
The closest we have to a roadmap would be our feature wishlist: https://github.com/rstudio/pins/projects/1

**Comment by javierluraschi** [comment]
Versions also got implemented in early 2020, closing this one.
