### ISSUE TITLE
Unclear on pin_get() documentation in kaggle boards

### ISSUE THREAD

**Issue by brshallo** [rstudio/pins#290]
Documenting a few things I did not find immediately clear when going through documentation.

**I. What pin_get() will return**

Reading through the [using kaggle boards](https://pins.rstudio.com/articles/boards-kaggle.html) documentation (as well as the `pin_get()` [reference page](https://pins.rstudio.com/reference/pin_get.html)) it wasn't always clear to me what `pin_get()` would return. 

For example, if it would load the data into R directly as shown at:

>`pin_get("iris-pin", board = "kaggle")`

Or if it would download the data and then return the location of the locally cached files, as shown at:

>`pin_get("c/crowdflower-weather-twitter", board = "kaggle")`

My assumption was that it will load data into R if reading from a YAML, and otherwise just download the data and return the cached file path...?

---

**II. Best practice on loading data into R when using pin_get()**

Also, in cases where `pin_get()` returns a local file path, is it best practice to wrap it in a read function, e.g.

`readr::read_csv(pin_get("daithibhard/us-electoral-college-votes-per-state-17882020", board = "kaggle"))`

or with multiple files to do this via `purrr::map()` as shown in #14 ?

I assume doing this is best-practice and that it's not re-downloading the data each time I call `pin_get()`, correct?

**Comment by javierluraschi** [comment]
> My assumption was that it will load data into R if reading from a YAML, and otherwise just download the data and return the cached file path...?

Correct.

> Also, in cases where pin_get() returns a local file path, is it best practice to wrap it in a read function, e.g.

That's up to you and perhaps more a question for [communinty.rstudio.com](https://communinty.rstudio.com). I'd say `readr::read_csv` is a better approach since it saves you from vectorizing this yourself, but there are other functions like `jsonlite::read_json` which I believe are not vectorized and would require `purrr:map()`.
