### ISSUE TITLE
Creating a pin from an app published on RStudio Connect

### ISSUE THREAD

**Issue by Alik-V** [rstudio/pins#294]
I want to create a simple data collection shiny app that will be published on RStudio Connect server.
The idea is to send the link to the shiny app to someone, they will open the app and enter a set of inputs, click the button once they are done and create a pin on the company RStudio Connect server. The data that they entered would then be used by another app. Could you please recommend a course of action here? Is it achievable with pins? Are there any security problems associated with this approach?
Here is a stripped down code for the data collection. I get an error trying to put it up on the server in this form (minus the redacted information).
```r
library(shiny)
library(shinyWidgets)
library(pins)
library(dplyr)

board_register_rsconnect(server = "https://connect.example.com", #our server name here
                         key = Sys.getenv("CONNECT_API_KEY")
                         )

ui <- pageWithSidebar(
  headerPanel("Data drop"),
  sidebarPanel(
    numericInputIcon(
      inputId = "number1",
      label = "Some number",
      icon = list("$"),
      value = NULL
    ),
    numericInputIcon(
      inputId = "number2",
      label = "Another number",
      icon = list("$"),
      value = NULL
    ),
    actionButton(
      inputId = "enter_data",
      label = "Press to enter data"
    )
  ),
  mainPanel()
)

server <- function(input, output) {
  observeEvent(input$enter_data, {
    df <- tibble(
      "List Vial" = input$number1,
      discount = input$number2
    ) %>%
      pin("data_drop", board = "rsconnect")
  })
}

shinyApp(ui, server)
```

Thanks!

**Comment by javierluraschi** [comment]
I think this is a question that solution engineers from RStudio Connect can help you answer if you contact support. But I would say that this is a valid use case, assuming data is not huge, and no, there should not be any security issues... just notice that the pin will be created with credentials specified in `board_register()`, so you would want to make sure that user is the right user to own the pins.
