### ISSUE TITLE
AWS Authentication Signatures?

### ISSUE THREAD

**Issue by cboettig** [rstudio/pins#304]
Hi @javierluraschi ,

Is pins using [AWS Signature Version 2](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html) headers or the [current, Version 4 header](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html)?  From the `s3_board` code, it appears to be construction an authorization header in the V2 format, 

```
Authorization: AWS AWSAccessKeyId:Signature
```

https://github.com/rstudio/pins/blob/f47c2512e0483a7e35e66bac696afc0f49539e5a/R/board_s3.R#L28

Instead of the V4 format, 

```
Authorization: AWS4-HMAC-SHA256 
Credential=AKIAIOSFODNN7EXAMPLE/20130524/us-east-1/s3/aws4_request, 
SignedHeaders=host;range;x-amz-date,
Signature=fe5f80f77d5fa3beca038a248ff027d0445342fe2855ddc963176630326f1024
```

Am I following that correctly?  Is there a reason for this or would you please consider moving to the V4 format for authentication?  

I am also unclear why the S3 URL is using `http` and not `https` by default, 

https://github.com/rstudio/pins/blob/f47c2512e0483a7e35e66bac696afc0f49539e5a/R/board_s3.R#L47

Can you fill me in or would you consider moving to HTTPS?  

(Among other concerns, I think these things would also be needed for #255. In fact, using the current signature method and allowing the user to configure the `host` base URL may be all that's necessary to resolve that as well!)

**Comment by javierluraschi** [comment]
Right, mostly since V2 is easy to implement... but yeah, this one is something we should fix soon. Are you actually experiencing a problem in S3 or mostly for compliance with MINIO?

Changing `HTTP` to `HTTPS` by default since this is obviously an oversight.

**Comment by cboettig** [comment]
Thanks for the quick reply!  I haven't actually tested against the AWS servers recently, but I believe V2 is slated for deprecation (starting with new AWS buckets) now, so I imagine this issue is not restricted to MINIO? https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#UsingAWSSDK-sig2-deprecation.

You probably know aws.signature package already implements both V2 and V4 (I'll also note that aws.s3 works with MINIO clients out-of-the-box) ....

**Comment by cboettig** [comment]
Fantastic that you have AWS v4 signature support now :tada: :tada: !   

I'll try and take a look at the minio implementation as well.  Thanks again for the really great work here.
