### ISSUE TITLE
Registering S3-Board with temporary credentials

### ISSUE THREAD

**Issue by christian-ew** [rstudio/pins#316]
Hey all,

I was wondering if there is a built-in method for using the board_register_s3 function not only with ACCESS_KEY and SECRET_ACCESS_KEY, but also with a SESSION_TOKEN. In the environment we develop currently we get an authorization-error if we only try to use the ACCESS/SECRET_ACCESS_KEY - Combo.

Thanks for the great package!

Kind regards,
Christian

**Comment by javierluraschi** [comment]
Currently not supported. If someone wanted to add this they would need to add a `session` parameter to `board_initialize.s3`, adding the parameter would store this `session` in `board$session` automatically, which can then be used in `s3_headers` to add the proper header. See: https://github.com/rstudio/pins/blob/master/R/board_s3.R
