### ISSUE TITLE
Issue retrieving a file with spaces on RStudio Connect

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#318]
Hi,

Awesome package! 

I noticed that I have issue when I pin a file that contains a space on Rstudio Connect
For example I have no problem pinning and retrieving this file 
     
           write_csv(mtcars,path="test 1.csv")

but I will not be able to this file via the pins package after I have pinned it

         write_csv(mtcars,path="test 1.csv")

thanks 

Iain

**Comment by javierluraschi** [comment]
This worked just fine for me, am I missing something?

```r
> readr::write_csv(mtcars,path = "test 1.csv")
> pin("test 1.csv", name = "test1csv", board = "rsconnect")
> pin_get(name = "test1csv", board = "rsconnect")
[1] "/Users/javierluraschi/Library/Caches/pins/rsconnect/javier.personal/test1csv/test 1.csv"
```

**Comment by javierluraschi** [comment]
Same if we run with an implicit name,

```r
> pin("test 1.csv", board = "rsconnect")
> pin_get("test_1", board = "rsconnect")
[1] "/Users/javierluraschi/Library/Caches/pins/rsconnect/javier.personal/test_1/test 1.csv"
```

Looks like we can safely close this, but feel free to open a new GitHub issue if needed.
