### ISSUE TITLE
Revisit mechanism for turning off versioning on rsconnect boards

### ISSUE THREAD

**Issue by colearendt** [rstudio/pins#324]
In #245 , there is an implementation that consists of _delete the content_.

IMO, we should be more judicious about deleting / recreating content, and instead purge old bundles using the bundle API. This way links / etc. are not broken

**Comment by javierluraschi** [comment]
Hi @colearendt,

Are we already doing this? See https://github.com/rstudio/pins/blob/master/R/board_rsconnect.R#L216-L222

So basically, we query the previous bundle versions, and we delete all the previous ones except the current one. Are we perhaps using an older version of `pins`?

**Comment by colearendt** [comment]
Ahh nice, thanks! That's perfect - I missed that! I was distracted by https://github.com/rstudio/pins/blob/2944c532b599dff83061942e1f9f9717abd4cb7f/R/board_rsconnect.R#L376 😅 

Thanks Javier!!
