### ISSUE TITLE
Getting Lexical Error with JSON Text while pinning the data to RS Connect

### ISSUE THREAD

**Issue by jayaraman94** [rstudio/pins#327]
I have tried pinning mtcars data set to my RS Connect using the below code,

pin(mtcars, description = "The motor trend cars data set", board = "rsconnect")

And I am getting this error statement below,

Error: lexical error: invalid char in json text.
<!DOCTYPE html PUBLIC "-//W3C//
(right here) ------^

I have tried pinning many data including my own data also. But, still it throws the same error.

Any comments or fix on this will be helpful.

Thanks,
Jay.

**Comment by javierluraschi** [comment]
Could you set `options(pins.verbose = TRUE)`, recreate the pin, and share the output log here to help you troubleshoot? Please make sure to remove any sensitive information from the log file.

**Comment by jayaraman94** [comment]
Hi Javier,

Thank you for your response.

I have tried setting options(pins.verbose = TRUE) and resetting the pin. But, still the same error is throwing again.

I have attached the output log here for your reference,
![output log](https://user-images.githubusercontent.com/76025464/102289389-a3c05c80-3f92-11eb-8b7d-982570735e53.png)

**Comment by jayaraman94** [comment]
Hi Javier

Good Day

The issue about the mentioned error regarding lexical error with Json text has been rectified.

"We've traced this down to a firewall error on the RStudio connect end. That was causing a 403 Authorisation Failed error which was returning the webpage instead of a valid JSON.
This issue is fixed but it would be nice if the entire "JSON" could be printed instead of just the top section, as it would make debugging a lot easier."

Thank you.
