### ISSUE TITLE
Getting Deployment failed issue for R Markdown File when depolying to rs connect, because of ODBC Connection error

### ISSUE THREAD

**Issue by jayaraman94** [rstudio/pins#344]
I have created a R Markdown file for updating data regularly in RS Connect.

My R Markdown file is running fine in R studio. But, when deploying that to RS Connect it is showing deployment failed error due to  the ODBC connection error.

Because, the odbc connection part is not running while deploying to RS Connect.

Any help with this will be appreciated.

Thanks,
Jay.

**Comment by javierluraschi** [comment]
Hi, this package is about `pins`, not `odbc` nor RStudio Connect. Could you try asking for help under [community.rstudio.com/](http://community.rstudio.com/)?
