### ISSUE TITLE
pin_get() fails with kaggle dataset that contains directory

### ISSUE THREAD

**Issue by Athospd** [rstudio/pins#348]
The code and the error follows:

``` r
pins::board_register_kaggle(token = "~/kaggle.json")
file <- pins::pin_get("c/birdsong-recognition", board = "kaggle", extract = TRUE)
#> Error in pin_download_one(p, ...): Client error: (404) Not Found. Failed to download remote file: https://www.kaggle.com/api/v1/competitions/data/download/birdsong-recognition/example_test_audio/ORANGE-7-CAP_20190606_093000.pt623.mp3
```

<sup>Created on 2021-01-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I can't tell if this occours due to some pin issue or due to kaggle's api issue. Google didn't help me, though =(

**Comment by hadley** [comment]
Smaller example with directories: https://www.kaggle.com/jpmiller/publicassistance

**Comment by hadley** [comment]
Can I ask what you're using this for?

**Comment by Athospd** [comment]
This dataset is related to my master's subject (bird detection through its songs, https://athospd.github.io/mestrado/). I'd to practice my modeling skills and also benchmark my experiments with it (along with other datasets).
Also, I would like to contribute to {torchdatasets}, which already has kaggle as one of their official "data CDN". See example here: https://github.com/mlverse/torchdatasets/blob/master/R/dogs-vs-cats.R

I tried to stick with their coding conventions, and that's the why I chose to use pins::*kaggle* related functions.

Thank you for your patience in trying understanding my English writing =P

**Comment by hadley** [comment]
I've fixed the underlying problem that causes this to fail, but it reveals a new problem — the kaggle API is rate limited. There's no clean way to do caching + rate limiting with httr, so this will have to wait until pins switches to httr2. Given that the kaggle board is relatively little used, I'm going close this issue in recognition of the fact it's unlikely to get high enough on my priority list to fix in the near future.
