### ISSUE TITLE
curl/httr error in get_pin() / pin_download_one() when file is inside a directory

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/pins#357]
In brief: when a pin contains a directory with files in it, `get_pin()` fails at the `pin_download_one()` call.

An end-to-end reprex would be hard to share since creating the pin would require the method I am implementing in a package: I am creating a custom pin method following the [Extending pins vignette](https://pins.rstudio.com/articles/pins-extending.html), specifically for Arrow datasets which require the data files to sit in a separate directory.

Below is a limited reprex that uses an [existing pin](https://github.com/petrbouchal/storage-public/tree/main/arrow_ds) created to have files nested in a directory:

``` r
library(pins)
github_public <- pins::board_register_github(repo = "petrbouchal/storage-public", branch = "main")
x <- pin_get("arrow_ds", board = github_public, cache = F)
#> Error in curl::curl_fetch_disk(url, x$path, handle = handle): Failed to open file /var/folders/c8/pj33jytj233g8vr0tw4b2h7m0000gn/T//Rtmp51LbdF/file142807b0d2611/arrow_files/part-0.parquet.
```

<sup>Created on 2021-01-29 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

The error occurs  in: https://github.com/rstudio/pins/blob/305bfbc2adfd8089151fa4bd3654c1fed2d3b705/R/pin_download.R#L99-L104

`destination_path` is correctly defined, but if it points to a file in a subdirectory, the `httr::GET()` call fails because that subdirectory has not been created.

I will submit my local fix as a PR for you to consider.

possibly related to #348

**Comment by hadley** [comment]
Closing this in favour of #427 — unfortunately the internals of pins are being overhauled in such a way that existing extensions will break.
