### ISSUE TITLE
Problem in datatxt_refresh_index when subpath is specified

### ISSUE THREAD

**Issue by lenafm** [rstudio/pins#359]
I could be completely wrong with this but I think the `httr::GET` part of `datatxt_refresh_index` fails when the subpath is not null (in my case this is because boards are 'folders' inside an AWS S3 bucket):

```
response <- httr::GET(index_url,
                                   httr::write_disk(temp_index, overwrite = TRUE),
                                   board_datatxt_headers(board, "data.txt"))
```

If I understand the code correctly, this fails because `board_datatxt_headers(board, "data.txt")` is only passed `"data.txt"` but it should have the subpath attached to it. 

In `datatxt_update_index` the `httr::GET` part works, because the index file does have the subpath attached to it:

```
response <- httr::GET(file.path(board$url, index_file_get),
                                   board_datatxt_headers(board, index_file_get))
```
where `index_file_get <- file_path_null(board$subpath, "data.txt")`.

**Comment by hadley** [comment]
I'm going to rewrite `board_s3()` from scratch in the near future, so this problem will be fixed along the way.
