### ISSUE TITLE
Support for figshare

### ISSUE THREAD

**Issue by jameslairdsmith** [rstudio/pins#361]
The [figshare](https://figshare.com) service seems exactly in tune with the spirit of pins. And supporting it would be particularly useful for academic research sharing. I don't know how much effort it would be involved; I can see there is already a [package](https://docs.ropensci.org/rfigshare/) wrapping the API from rOpenSci.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
