### ISSUE TITLE
pin_changed_time (pin_reactive) not working when subpath specified in Azure board

### ISSUE THREAD

**Issue by mortandersen** [rstudio/pins#362]
Hi

I see that there seem to be some problems with the whole subpath system, and I just wanted to add that there is also a problem with the `pin_reactive()` when using a subpath folder system in the Azure board. See the following code:

```
> pins:::pin_changed_time("name_xyz", board = "azure", extract = TRUE);  now("CET") 
[1] "2021-02-10 14:43:53 CET"
[1] "2021-02-10 14:43:53 CET"
```

I have the newest developer version from Github.

Thanks.

**Comment by mortandersen** [comment]
Actually, it is not just with subpaths. I have just adjusted my code such that it no longer uses subpaths and the same problem with `pins:::pin_changed_time` always being the current time persists.

**Comment by hadley** [comment]
I can't see how the logic in `pin_reactive()` ever worked, but I've implemented `pin_reactive_read()` and `pin_reactive_download()` that will work with modern boards using the new standard `created` metadata field.
