### ISSUE TITLE
App won't load in documentation page at bottom on line 53

### ISSUE THREAD

**Issue by philbowsher** [rstudio/pins#363]
https://github.com/rstudio/pins/blob/08ae23a3cf76fdd49800b48162f3d8839b4713ca/vignettes/use-cases/update-plumber-and-shiny-apps.Rmd#L53

RSC app won't load in RSC

**Comment by akgold** [comment]
beta.rstudioconnect.com is not meant for stable public use. If we want to host these assets somewhere public, it should probably be on colorado.rstudio.com. Thoughts, @colearendt? I'm happy to migrate.

**Comment by colearendt** [comment]
That's a great question... I can see the value in beta since anyone can have an account there. Colorado has the benefit of consistency. For the purposes of "Connect Demo," Colorado does seem to be the better fit. 🤷‍♂️  I'm ambivalent 😄 But definitely fine w/ however you'd like to proceed!

**Comment by akgold** [comment]
All the examples here point to the pin itself/an app already deployed on RSC as an example (as opposed to pinning afresh). So I'd think putting somewhere stable for people to see example is probably the best course here. Going to migrate to Colorado and make PR to docs later this week.

**Comment by hadley** [comment]
It feels to me like like all four use cases could be combined into a single vignette that told one longer story. What do you think?

**Comment by akgold** [comment]
I think one use cases vignette would make a lot of sense.
