### ISSUE TITLE
azure_headers function leads to error when LC_TIME locale is not English

### ISSUE THREAD

**Issue by hlynurhallgrims** [rstudio/pins#365]
I've been having trouble trying to pin data to our Azure datalake. When trying to pin to Azure I've been getting a 403 error `The Date header in the request is incorrect.`

This was only happening locally, and not when running code in RStudio Connect, and after some digging around (shoutout to @colearendt for teaching me how to properly debug this type of thing) I've come to the realization that the error lies in the way the `date` object gets created in the azure_headers function. 

`format(Sys.time(), "%a, %d %b %Y %H:%M:%S %Z", tz = "GMT")`

Is it possible to input something into the format function to force the locale to be English, rather than the users default language/time format? If not, I feel like it could be a good idea to explicitly state it in an error message that LC_TIME needs to be set to "en_US.UTF-8" or similar.

Reprex follows.

``` r
## ICELANDIC

# This is my default system setting
Sys.setlocale("LC_TIME", "is_IS.UTF-8")
#> [1] "is_IS.UTF-8"

# This is what then gets defined as the date within azure_headers()
format(Sys.time(), "%a, %d %b %Y %H:%M:%S %Z", tz = "GMT")
#> [1] "mán, 15 feb 2021 22:25:58 GMT"

library(pins)
board_register_azure(container = "data",
                     account = "datalake", 
                     key = "my_key_removed",
                     path = "Sandbox")

pin(mtcars, "mtcars", board = "azure")
#> Error in datatxt_upload_files(board = board, name = name, files = upload_files, : Failed to upload 'data.csv' to 'https://stddatalake.blob.core.windows.net/data/Sandbox/mtcars/data.csv'. Error: <?xml version="1.0" encoding="UTF-8"?>
#> <Error>
#>   <Code>AuthenticationFailed</Code>
#>   <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
#> RequestId:fd34161c-401e-0036-50e9-030674000000
#> Time:2021-02-15T22:25:58.8772855Z</Message>
#>   <AuthenticationErrorDetail>The Date header in the request is incorrect.</AuthenticationErrorDetail>
#> </Error>

## US ENGLISH

Sys.setlocale("LC_TIME", "en_US.UTF-8")
#> [1] "en_US.UTF-8"

# This is what then gets defined as the date within azure_headers()
format(Sys.time(), "%a, %d %b %Y %H:%M:%S %Z", tz = "GMT")
#> [1] "Mon, 15 Feb 2021 22:25:58 GMT"

board_register_azure(container = "data",
                     account = "datalake", 
                     key =  "my_key_removed",
                     path = "Sandbox")

#Look ma, no error! :-)
pin(mtcars, "mtcars", board = "azure")
```

<sup>Created on 2021-02-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by colearendt** [comment]
Thanks so much for the reprex! This will be very helpful to ensuring that we do a better job of crossing locales!
