### ISSUE TITLE
Pin Metadata

### ISSUE THREAD

**Issue by akgold** [rstudio/pins#369]
Allow metadata to be included on pin. 

Useful examples include:
* Data dictionary for what's in pin
* Column definitions for pin
* SHA of data itself (current version is SHA of entire bundle)
* Data on where (aka by what content) pin is being created/used on RSC
* Tags on the pin

**Comment by smingerson** [comment]
I think its a bug, but you can pass metadata right now. It's not surfaced on the RSConnect pin page, but is available via `pins::pin_info()`.
```r
pins::pin(mtcars, "mtcars", board = "your_rsc_board", 
              metadata = list(message = "hi"))
pins::pin_info("mtcars")
```
This will overwrite the default nrow/ncols data.
