### ISSUE TITLE
AWS S3 credential handling

### ISSUE THREAD

**Issue by jcheng5** [rstudio/pins#373]
Currently, AWS credential handling is limited to either reading `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY` environment variables or having the user explicitly pass these values into `board_register_s3`. The expectation for AWS (based on AWS CLI tools and every AWS SDK) is generally that it should try a whole bunch of ways to access, including:

* [Config files](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html), possibly including profiles, possibly assuming roles
* Using an [external process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html)
* [EC2 Instance Metadata Service](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-metadata.html), and similar services for ECS/EKS

Consider using paws.storage for S3 access, it will handle all of this.

**Comment by jpmarindiaz** [comment]
The package `aws.s3` could also be a good option for handling the AWS S3 part
https://github.com/cloudyr/aws.s3

**Comment by hadley** [comment]
More info at https://github.com/paws-r/paws/blob/main/docs/credentials.md

**Comment by hadley** [comment]
And explore encryption at least.
