### ISSUE TITLE
Tooltip or Labels to appear in visnetwork when the node is selected and disappear when node is deselected

### ISSUE THREAD

**Issue by jayaraman94** [rstudio/pins#376]
Hi Team,

I am building a R shiny app with visnetwork visualization. And the user has a requirement of making tooltips or labels to appear when the node is selected and disappear when the node is deselected. If the user selects multiple nodes, the tooltip or label must stay for those multiple nodes and that would be easy for user to take a snip for their reporting purpose.

For this I have verified many documents related to visEvents but I couldn,t find any. Also, I have a visnetwork javascript file, where I have managed to change some EventListeners and functions, but I couldn't get the desired result yet.

I have attached the screenshot of my js file below for your reference.

![image](https://user-images.githubusercontent.com/76025464/109082390-ffa81e00-7757-11eb-9460-757fef529727.png)

It would be good if I could get this working.

Also, I have tried exporting the entire R shiny App as PDF. But, I am getting only the plots. Instead, I need the entire app with same alignment including the tabpanel and the title. 

Any help on this is also much appreciated.

Thanks,
Jay.

**Comment by loganbwu** [comment]
This issue looks like it's related to the [visNetwork ](https://github.com/datastorm-open/visNetwork)package, not the pins package.
I'll discuss with you privately - just leaving this comment here for anyone who stumbles across it.
