### ISSUE TITLE
Wrong pin content url computed for rsconnect board leading to download error

### ISSUE THREAD

**Issue by cderv** [rstudio/pins#379]
It could be a edge case because it happens if the url contains a part close to server url 

I stumble upon this on `bookdown.org` while naming the pin `bookdown.org-book-meta`. 

Here is a reprex with a dummy dataset

``` r
pins:::rsconnect_remote_path_from_url(list(server = "bookdown.org"), "https://bookdown.org/cderv/bookdown_org-mtcars/")
#> [1] "-mtcars"
pins:::rsconnect_remote_path_from_url(list(server = "bookdown.org"), "https://bookdown.org/cderv/mtcars/")
#> [1] "/cderv/mtcars"
```

<sup>Created on 2021-03-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9002)</sup>

This happens because the name of the server is used in a `gsub` as a regex string

https://github.com/rstudio/pins/blob/4bef24b6c1783faa0f3151828195ac25ae7dabe0/R/board_rsconnect.R#L328-L334

This means that the `.` in server url will be interpreted as regex dot, leading to `bookdown-org` being matched, and then the remote path being truncated. 

It is easy to workaround but still something not right with the way the remote path is computed from the url.

````r
> packageVersion("pins")
[1] ‘0.4.5.9000’
````

**Comment by hadley** [comment]
Part of #366 maybe?

**Comment by hadley** [comment]
This has now been implemented in a completely different way, and I'm not sure what the buggy code now corresponds to. I do much less weird regexing of urls now, so it should be fixed, but if not, please open a new issue.

**Comment by cderv** [comment]
Great. Let's close this then. We'll see. thanks !
