### ISSUE TITLE
Add slug parameter in pin creation?

### ISSUE THREAD

**Issue by jpmarindiaz** [rstudio/pins#387]
I have seen multiple issues that involve changing or renaming a pin, a slug is automatically created for all pins according to their name and some regex rules. This may cause unexpected behavior when saving and retrieving pins. Here some use cases I have can think of or seen personally:

- Users may simply want to rename the pin (but not the original path of the file) for discovery purposes
- Users may want to save a whole new pin inside the same board that happens to create the same slug for different data (say `data&pública.csv`  and `DATA publica.csv`  -> `data-publica.csv`). Yes, not all data users in out there have seen the naming things presentation by Jenny Bryan.
- Users may want to keep their original language in naming files and adding descriptions for improving accessibility but have more control on how their URL is built (Здравствуйте -> hello.csv)

**Comment by hadley** [comment]
What is a slug in this context?

**Comment by jpmarindiaz** [comment]
What I mean by slug is that the actual `name` of the pin is actually converted to a "clean name" in the pin creation and in practice it works as a slug if you see the pin in an URL. 
I suggest having more flexibility for the user to choose how the pin will be saved with a clean name, perhaps this would clarify what I mean by slug:

```
pin(cars)
# would create
# /Users/username/Library/Caches/pins/local/cars 

pin(cars, name = "My cars")
# would create
# /Users/username/Library/Caches/pins/local/my-cars 

pin(cars, name = "My!cars", slug = "my-cars2")
# would create 'my-cars-2' so not to overwrite 'my-cars'
# /Users/username/Library/Caches/pins/local/my-cars-2 

```

**Comment by hadley** [comment]
I think you're talking about the directory name where the pin is stored?

**Comment by jpmarindiaz** [comment]
Yes, if you are in a local board. If you are in say Amazon S3 then it would be a URL slug (as the whole folder gets copied from the local file system to the remote board).

**Comment by hadley** [comment]
Thinking about this more, I think it might be simpler to require that pin names be valid paths, and simply remove the existing munging.

**Comment by jpmarindiaz** [comment]
Makes sense. Additional information for human readable`titles` or whatever users want to include may go in the `meta` properties, I guess description is also fine as it is with whichever text the user wants to include

**Comment by hadley** [comment]
FYI the behaviour of `pin()` probably won't change, but `pin_write()` does not munge the file name.
