### ISSUE TITLE
S3 board cannot be outside amazonaws.com

### ISSUE THREAD

**Issue by laurivaltteri** [rstudio/pins#388]
There might be a problem with `host` and `region` parameters working as supposed to?
```R
pins::board_register_s3(
    bucket = "pinsdemo",
    key = aws.signature::locate_credentials()$key,
    secret = aws.signature::locate_credentials()$secret,
    host = "https://s3.somewhere.else.com",
    region = "eu-west-1"
)
```
Results a following error:
```
> pin(iris, board = "s3")
Error in datatxt_upload_files(board = board, name = name, files = upload_files,  : 
  Failed to upload 'data.csv' to 'https://pinsdemo.s3.amazonaws.com/iris/data.csv'. Error: <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AuthorizationHeaderMalformed</Code>
  <Message>The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1'</Message>
  <Region>us-east-1</Region>
  <RequestId>HR31408B2QWGJV4B</RequestId>
  <HostId>xv986kZZywxLasyvljSJIPmyRsw78iiFRhkuyQ0FpgBYTJVcEu878g5txJk3jOen2LWCqQlN9IY=</HostId>
</Error>
```

Both the url and the header are wrong with this attempt.

**Comment by hadley** [comment]
Just from looking at the default arguments, I wonder if adding the `https://` is causing problems. The default value of `host` is `"s3.amazonaws.com"`.

**Comment by laurivaltteri** [comment]
I did try also without the prefix. I guess it could also be the newer header function, since I found a workaround by using solution described here:
https://github.com/rstudio/pins/issues/172#issue-562147055

**Comment by laurivaltteri** [comment]
Now it broke down at least for my S3 service. Peculiar indeed, I didn't even update anything. Provably Ceph was updated, and now it's not compatible with AWS.

**Comment by hadley** [comment]
FWIW I'm planning on rewriting `board_s3()` to use paws.storage, instead of rolling it by hand.

**Comment by laurivaltteri** [comment]
Amazing! The new `board_s3()` function works now perfectly with our S3 service! No need for extra layer of code anymore 👌
