### ISSUE TITLE
Move blog posts to RStudio blog

### ISSUE THREAD

**Issue by hadley** [rstudio/pins#394]
All links on https://pins.rstudio.com/blog/index.html are broken, so this is going to go away in the short term but needs to be recreated in the long term. Source is `blog/` directory.

**Comment by jthomasmock** [comment]
I'm interested in this

**Comment by hadley** [comment]
Thanks @jthomasmock — is it obvious what to do next, or should I give a rough outline of what I think you should do?

**Comment by jthomasmock** [comment]
Hi @hadley - would love an outline to confirm my assumptions and make some progress here.

Working assumption is I can start work to move the blog posts into the main RStudio blog.

**Comment by hadley** [comment]
I think all you need to do is move the three blog posts from the blog directory to the RStudio blog, updating the metadata so it works with hugodown instead of distill. The blog posts look like they're `.Rmd`, but they're really actually `.md` since the results of running the code is already embedded, that should mean that you don't need to worry about getting the old code running.

**Comment by jthomasmock** [comment]
Worked with @EconomiCurtis - the blogposts will be transferred to RStudio main blog as `.md` files. Curtis and I will update here once they're live and issue can be closed.

**Comment by hadley** [comment]
Thanks! 🥳

**Comment by jthomasmock** [comment]
The initial branch is ready to go on the dev branch thanks to @EconomiCurtis 

* [`pins` 0.2](https://deploy-preview-488--rstudio-blog.netlify.app/2019/09/09/pins-0-2-0-pin-discover-and-share-resources/)
* [`pins` 0.3](https://deploy-preview-488--rstudio-blog.netlify.app/2019/11/28/pins-0-3-0-azure-gcloud-and-s3/)
* [`pins` 0.4](https://deploy-preview-488--rstudio-blog.netlify.app/2020/05/29/pins-0-4-0-versioning/)

Note that given the articles are being improved and condensed we are going to change links from various references to `azure-articles`, `kaggle-articles`, etc to their respective reference function pages instead.

**Comment by hadley** [comment]
I wouldn't bother fixing the broken links TBH; I think blog posts are fundamentally ephemeral.  Thanks for all your work on this!

**Comment by hadley** [comment]
(One thing I did spot is that `{width=60%}` etc is appearing in the rendered posts; you might want to remove that)

**Comment by jthomasmock** [comment]
This has been completed, we ended up changing some links, and correcting the width() that was printing as well.

Issue ready to close.

**Comment by hadley** [comment]
Thanks @jthomasmock! Can you give me the links, then I'll add as news bullets to the pkgdown site and close this issue 😄

**Comment by jthomasmock** [comment]
Links below, live on the RStudio blog.

* [0.4 release, 2020-05-29](https://blog.rstudio.com/2020/05/29/pins-0-4-0-versioning/)
  * `https://blog.rstudio.com/2020/05/29/pins-0-4-0-versioning/`
* [0.3 release, 2019-11-28](https://blog.rstudio.com/2019/11/28/pins-0-3-0-azure-gcloud-and-s3/)
  * `https://blog.rstudio.com/2019/11/28/pins-0-3-0-azure-gcloud-and-s3/`
* [0.2 release, 2019-09-09](https://blog.rstudio.com/2019/09/09/pin-discover-and-share-resources/)
  * `https://blog.rstudio.com/2019/09/09/pin-discover-and-share-resources/`
