### ISSUE TITLE
pin() should give more information about what it's doing

### ISSUE THREAD

**Issue by hadley** [rstudio/pins#40]
Not sure exactly how much information is needed, but I think at least indicating that it's being downloaded or retrieved from local cache is important.

e.g. 

```R
url <- "https://raw.githubusercontent.com/facebook/prophet/master/examples/example_retail_sales.csv"

pins::pin(url)
# Downloading https://raw.githubusercontent.com/.../example_retail_sales.csv
# Caching to /tmp/example_retail_sales
pins::pin(url)
# Retrieving url from local cache
```

**Comment by javierluraschi** [comment]
So, there is a `options(pins.verbose = TRUE)` option that would do that... but is not documented so I'll add that.

**Comment by jpmarindiaz** [comment]
Should this option set to TRUE be the default behavior? 
And perhaps include more informative messages? Where is the local board in my machine?

I personally don't like it when stuff gets downloaded to my computer but I don't know where it is kept. It would be nice to have clearer messages so users don't have to read extensive documentation to know what's happening behind the scenes.

Screenshot pins v0.4.0
![image](https://user-images.githubusercontent.com/1489570/79929400-33653980-840b-11ea-9d54-deff1d071663.png)

**Comment by javierluraschi** [comment]
I'm closing all issues that could be postponed, while this one is reasonable, closing for now.
