### ISSUE TITLE
old bundles are now removed by default in connect board

### ISSUE THREAD

**Issue by cderv** [rstudio/pins#410]
I encountered a change in behavior recently. It seems that for rsconnect board now `pins::pin()` will automatically remove old bundled versions of pins and only one will be kept. It seems to me a pretty big change because I lost all the old bundled I wanted to keep initially. 

It seems this is because of 
https://github.com/rstudio/pins/blob/421fe6d7e577a0480aca3a6d26ac35672d8e3dd7/R/board_rsconnect.R#L247-L250
which then will trigger the deletion
https://github.com/rstudio/pins/blob/421fe6d7e577a0480aca3a6d26ac35672d8e3dd7/R/board_rsconnect.R#L320-L329

So `board_versions_enabled` seems to have change for default rsconnect board.
I confirm that with this code between two versions (see below reprex)
```r
rsc_key <- Sys.getenv("RSC_BOOKDOWN_ORG_TOKEN", unset = "")
board_register_rsconnect(server = "https://bookdown.org", key = rsc_key)
board <- board_get("rsconnect")
board_versions_enabled(board, TRUE)
```

I did a bisect and I think this comes from the rewrite in https://github.com/rstudio/pins/commit/16ff9ea546ba806c3c8e43f643367206c5ca2a73 where `versions = FALSE` by default which it may not have been the case before. 

Bisect was not exact because of https://github.com/rstudio/pins/commit/436e961c51eb21c8c0b591daae747bfad284afa3 which created error in code. This is with this commits a14c095feef85ee8a5ab03866b21b17e56e856d2, 16ff9ea546ba806c3c8e43f643367206c5ca2a73, 6779a7bf681f2a2e44d6ec1fb285b5b9196b9457, 436e961c51eb21c8c0b591daae747bfad284afa3

<details>
<summary>Reprex to run in the pins project after setting the env var (or change value in function call)</summary>

```r
system("git checkout cc6697279ae8bd19293585a8850bc0f5afff6baa")
#> [1] 0
devtools::load_all(".")
#> i Loading pins
rsc_key <- Sys.getenv("RSC_BOOKDOWN_ORG_TOKEN", unset = "")
board_register_rsconnect(server = "https://bookdown.org", key = rsc_key)
board <- board_get("rsconnect")
board_versions_enabled(board, TRUE)
#> [1] TRUE
system("git checkout 436e961c51eb21c8c0b591daae747bfad284afa3 ")
#> [1] 0
devtools::load_all(".")
#> i Loading pins
rsc_key <- Sys.getenv("RSC_BOOKDOWN_ORG_TOKEN", unset = "")
board_register_rsconnect(server = "https://bookdown.org", key = rsc_key)
board <- board_get("rsconnect")
board_versions_enabled(board, TRUE)
#> [1] FALSE
# restore branch to master
gert::git_branch_checkout("master")
```

</details>

This seems a pretty big change and this could cause issue for a lot of RStudio Connect users that where relying on bundles being saved. Currently, the workaround is to explicitly change the board registration to set version to TRUE. 
```r
board_register_rsconnect(server = "https://bookdown.org", key = rsc_key, versions = TRUE)
```

Is this change intentional that old behavior has changed ? 

I know the previous way is deprecated and that there is a new way (from https://pins.rstudio.com/reference/board_register.html) but it seems to be the same

``` r
rsc_key <- Sys.getenv("RSC_BOOKDOWN_ORG_TOKEN", unset = "")
board <- board_rsconnect(server = "https://bookdown.org", key = rsc_key)
board$versions
#> [1] FALSE
board_versions_enabled(board, TRUE)
#> [1] FALSE
```
it requires now 
```r
board <- board_rsconnect(server = "https://bookdown.org", key = rsc_key, versions = TRUE)
```
where the `versions` argument is not really documented in `?board_rsconnect`

Hope this quick digging help solves this. 
I think RStudio Connect should support bundle versions by default. And I think this is a breaking change that could cause issue with all existing code because bundles will be remove - I don't think we should do that. 

Also it could have effect with other board.

**Comment by hadley** [comment]
Yeah, sorry, you really shouldn't be using the dev version right now because it's in the middle of an upheaval.

For future reference, there's no need to do this level of investigation, just ping me here or on slack and I'll look into it.

**Comment by cderv** [comment]
Using dev version was a remain of previous issue I had with CRAN version. I changed my code to not use dev anymore. 

Next time I'll report first before looking. It is just that I often look into to be sure it is a something related to the package and not something I missed on my side. And sometimes it leads me pretty deep.

BYW I found another puzzling behavior. I'll just report this one with a small reprex.

**Comment by iainmwallace** [comment]
I would second the idea that RStudio Connect pins would save versions by default - it is a really useful default behaviour across the Connect platform. It may be useful to have a warning that versions are enabled for large pins.

It would also be very beneficial to have some guidance on how best to configure Connect with pins to avoid automatic bundle cleaning up which I believe may happen if space becomes an issue. The use case is that in situations where you really need to keep all version of a dataset (for auditing purposes etc), Connect + pins is a suitable solution.

**Comment by hadley** [comment]
@iainmwallace this was a unfortunate combination of two bugs, it is not a design change.
