### ISSUE TITLE
Error / warn on an empty pin publish

### ISSUE THREAD

**Issue by colearendt** [rstudio/pins#415]
IIRC this was related to #413 

If a user publishes a pin that is "empty" or retrieves a pin that is "empty" (i.e. as a result of broken `zip` behavior), there should be warning / messaging as such. Otherwise, (particularly for non-dataset pins) it can be very tricky to determine what is being retrieved and whether it was what is expected (i.e. if what you expect is a binary object, you do not expect it to be printable anyways).

**Comment by hadley** [comment]
I think we'll just avoid this upstream. I don't think it's worth retrofitting better behaviour to already broken published pins, we'll just avoiding publishing broken pins in the future. So please file issues when you find a reprex that creates a broken pin.
