### ISSUE TITLE
Ability to rename data.csv for download of pin from RStudio Connect interface

### ISSUE THREAD

**Issue by loomalaine** [rstudio/pins#417]
When using pins to share data with colleagues who are not using R or python, but instead are downloading csvs, it would be helpful to have the option of renaming the download file for them (or perhaps by default as the name of the pin?)

**Comment by hadley** [comment]
Why?

**Comment by loomalaine** [comment]
@hadley The use case I'm imagining is that we want to share a handful of related data frames with people. (This is common for us when there is some ad hoc analysis where we need to do most of the data preparation but a subject matter expert is going to make the final decisions about how to summarize and present the data.) If we share three pins with them with the expectation that they'll download the csv files and go from there, it seems inconvenient for them to have to download and rename each one. Especially if there might be updates to the pins that they need to re-download later on, it would be nice to have the filenames upon download be consistent with the pin name to make them easier to keep track of and link back to the pin of origin.

And I see that I said in the issue title "from RStudio Connect interface", but it might not make sense to do this manually, or at least not as the only method. It could be set programmatically at the pin level, or perhaps be a global option for all pins on the RSC server.

**Comment by hadley** [comment]
Why would they need to rename them? Ooooh, because they're always named `data.csv`? Maybe they should be called `{pin_name.csv}` by default?

**Comment by loomalaine** [comment]
Yep, exactly!

**Comment by jpmarindiaz** [comment]
perhaps it would also help those pins who happen to be folders with multiple files

**Comment by hadley** [comment]
@jpmarindiaz what currently happens to those files?
