### ISSUE TITLE
pin_info() does not make it clear when multiple pins with name exist

### ISSUE THREAD

**Issue by loomalaine** [rstudio/pins#418]
If there are two pins (pinned by different users) with the same name, pin_info() only returns info on one of them. This seems misleading. Alternatively, if I use connectapi::get_content() I can see that there are two pins with the same name.

**Comment by hadley** [comment]
The problem is that `pin_info()` is started from `pin_find()` rather than using the same code path as `pin_get()`. I think I will resolve this by introducing a new `pin_metadata(board, name)` (which also resolves the argument order problem).

**Comment by hadley** [comment]
I don't really understand the `pin_info()` interface at all — I think `pin_meta()` should be easier to use, but please let me know if I've missed anything.
