### ISSUE TITLE
Tag pins on RSC

### ISSUE THREAD

**Issue by hadley** [rstudio/pins#421]
i.e. via <https://docs.rstudio.com/connect/api/#post-/v1/content/{guid}/tags> and friends

**Comment by hadley** [comment]
Lets wait until the RSC api is a bit more mature for this.

**Comment by ryan-gsc-garnett** [comment]
Looking forward to the time when we can add tags to pins when adding to Connect....
https://community.rstudio.com/t/add-tags-when-publish-pin/120376
