### ISSUE TITLE
Offline access to pins stored in rsconnect

### ISSUE THREAD

**Issue by slohr** [rstudio/pins#423]
I've noticed that pins stored to a corporate RStudio Connect server do not interrogate the local cache for subsequent gets when the Connect server is not available.  My expectation was that they would be retrieved from the local cache if the URL was not accessible.

<details>

Is this intended behavior?

Here are the specific errors that I get when the Connect server is no longer accessible:

"Error in curl::curl_fetch_memory(url, handle = handle) : Timeout was reached: [connect.alkahest.io] LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60"

or

"Error in curl::curl_fetch_memory(url, handle = handle) : Could not resolve host: connect.alkahest.io"

A few more details about how this problem arises:

I'm storing and retrieving pins over a VPN connection to a corporate RStudio Connect server. Sometimes that VPN connection is not available for a variety of reasons and I will work locally.

Below is a simple example that flushes out the issue and demonstrates fetching the data manually from cache. It assumes you can make the RStudio Connect server "go away" at one point.

thx!
scott

```{r}
library(pins)
library(tibble)
```

Register the local Connect server (In this example the real server has been replaced with connect.example.com).

connect_version: 1.8.4.2-2

```{r}
pins::board_register("rsconnect", server = "https://connect.example.com")
```

The API key approach is being used so the following *.Renviron* entry is present and was created under the *scicompadmins* Connect account.

    CONNECT_API_KEY=dbiZ9x7qZpqP..blah...blah

Create data for pin

```{r}
my_test_data <- tibble::tribble(
  ~a, ~b, ~c,
  "a1", "b1", "c1",
  "a2", "b2", "c1"
)
my_test_data
```
Now pin

```{r}
pins::pin(
  my_test_data,
  name = "scicompadmins/my_test_pin_data",
  board = "rsconnect"
)
```

Now get the data back (while on VPN)

This will work.

```{r}
roundtrip_on_vpn <- pins::pin_get("scicompadmins/my_test_pin_data", board = "rsconnect")
roundtrip_on_vpn
```

Now disconnect from VPN (or someother way of making connect.example.com not accessible) and try to get the pin.

This will fail.

```{r}
roundtrip_off_vpn <- pins::pin_get("scicompadmins/my_test_pin_data", board = "rsconnect")
roundtrip_off_vpn
```

One of two errors can happen here:

    Error in curl::curl_fetch_memory(url, handle = handle) : Timeout was reached: [connect.example.com] LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60

or

    Error in curl::curl_fetch_memory(url, handle = handle) : Could not resolve host: connect.example.com

I would have expected the PINS package to catch these errors and interrogate the local cached version.

So let's see if we can manually reconstruct from the local cache (VPN still disconnected)

```{r}
connect_board <- pins::board_get("rsconnect")
roundtrip_from_cache <- readRDS(
  file.path(
    connect_board$cache,
    connect_board$board,
    connect_board$account,
    "my_test_pin_data",
    "data.rds"
  )
) %>% tibble::as_tibble()
roundtrip_from_cache
```

This works with the intended result.

</details>

**Comment by hadley** [comment]
A few notes to self about how we might implement this:

Cached rsconnect pins are now stored in `fs::path(board$cache, paste0(content$guid, "_", bundle_id))` so we'd need to cache some a mapping between `name` and `guid` + `version`. Then would need to decide what specific errors indicate that we should use the cache — is it all errors, or just curl errors (which [aren't currently typed](https://github.com/jeroen/curl/issues/154))

**Comment by hadley** [comment]
I do worry that automatically falling back to the cache version might mean that if something went wrong with auth you might be using old cached data for a long time without realising it. Maybe it would be better to explicitly opt-in with some sort of `offline` option?

**Comment by slohr** [comment]
That occurred to me too when you mentioned that curl errors aren't explicitly typed. A lot of room for silent errors. I went down the rabbit hole of doing a pre-flight HEAD check and nothing seemed clean enough.

I'd be happy with an explicit opt-in. Pretty obvious what's happening and if-and-when the server is available it could provide a gentle nudge that you're working on a stale version if a new one is available. Or maybe with this option it just swallows the curl errors  to keep it simple.

I could also see leveraging the versions infrastructure and if there's an error you can query the cached version identifier and put that in the request. So offline type of behavior is only available when accessing explicit versions. Presumably the version semantics make it safe to be offline since what's local should be the same as remote.

**Comment by hadley** [comment]
Good thought about the versioning — I _think_ if everything is cached correctly, a versioned `pin_read()` should just work when offline, because it won't need to access RSC at all.

I'm experimenting with an `offline` argument that will always used cached values.

**Comment by hadley** [comment]
@jcheng5 suggested what I think is the right compromise: the board gains an `use_cache_on_failure` argument that defaults to `is_interactive()` — this means it will be TRUE for interactive exploration, but FALSE for automated scripts.

**Comment by hadley** [comment]
See implementation in `board_url()`; just need to copy logic to `board_rsconnect()`.

**Comment by slohr** [comment]
I've tested with the legacy API and my above example now works (save for needing to add versions = TRUE to the board_register call). Thanks!!!

But now that I'm attempting to migrate to the 1.0.0 API the cache behavior is no longer working. In addition, now that you need to pass around a "board" object it fails at an earlier stage in the process. Perhaps I'm not adapting my code properly to use this feature in the API?

Here's my test case:

```{r}
board <- pins::board_rsconnect(
  auth="manual",
  server="https://connect.example.com",
  account="the_username_to_be_used",
  key = "An_API_key_in_Renviron",
  use_cache_on_failure = TRUE #forcing for testing
)
```

Same test data
```{r}
my_test_data <- tibble::tribble(
  ~a, ~b, ~c,
  "a1", "b1", "c1",
  "a2", "b2", "c1"
)
my_test_data
```

Write with the new API
```{r}
board %>% pins::pin_write(
  my_test_data, 
  "my_test_pin_data"
)
```

Now retrieve
```{r}
board %>% pins::pin_read(
  "my_test_pin_data"
)
```

However if you disconnect VPN so that the URL is not accessible then you get this error:

Error in curl::curl_fetch_memory(url, handle = handle) : Timeout was reached: [connect.alkahest.io] LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60

traceback

```
20.
curl::curl_fetch_memory(url, handle = handle)
19.
request_fetch.write_memory(req$output, req$url, handle)
18.
request_fetch(req$output, req$url, handle)
17.
request_perform(req, hu$handle$handle)
16.
httr::GET(board$url, path = path, query = query, auth, ...)
15.
rsc_GET(board, "v1/content", list(name = name$name))
14.
rsc_content_find(board, name)
13.
pin_meta.pins_board_rsconnect(board, name, version = version)
12.
pin_meta(board, name, version = version)
11.
pin_fetch.pins_board_rsconnect(board, name, version = version, ...)
10.
pin_fetch(board, name, version = version, ...)
9.
pins::pin_read(., "my_test_pin_data")
8.
function_list[[k]](value)
7.
withVisible(function_list[[k]](value))
6.
freduce(value, `_function_list`)
5.
`_fseq`(`_lhs`)
4.
eval(quote(`_fseq`(`_lhs`)), env, env)
3.
eval(quote(`_fseq`(`_lhs`)), env, env)
2.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1.
board %>% pins::pin_read("my_test_pin_data")
```

```{r}
> packageVersion("pins")
[1] ‘1.0.1’
> 
```
