### ISSUE TITLE
Board for Box folder

### ISSUE THREAD

**Issue by justinmillar** [rstudio/pins#425]
I was wondering if there currently exists, or are plans to have a board for shared Box folders? 

For my use case, I have an internal R package for accessing processed outputs, and I would like to have the package be able to access the up-to-date pinned outputs. This would allow me to regularly update outputs without requiring the user to have a local instance of the Box folder (or store the data directly in the package, which would been to be constantly update the package).

Thanks!

**Comment by hadley** [comment]
No, sorry, and it's currently out of scope for pins. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
