### ISSUE TITLE
Default branch for board_register_github() is 'master' not 'main'

### ISSUE THREAD

**Issue by MarkEdmondson1234** [rstudio/pins#443]
Now the default GitHub branch has changed, after I made a new GitHub repo to test the `board_register_github()` I had to add the `branch="main"` argument to make the first example work:

```r
board_register_github(repo = "username/repo", branch = "main")
```

I guess the default should change when branch=NULL.

**Comment by hadley** [comment]
This is now a legacy board, so I'll only be making critical bug fixes in the future.
