### ISSUE TITLE
Allow `/` in pin names

### ISSUE THREAD

**Issue by hadley** [rstudio/pins#453]
For lightweight namespacing. Will need to carefully check that don't contain `..` etc.

**Comment by EKtheSage** [comment]
I am curious if adding `/` to the name will in effect create a subdirectory?

This may be what I am trying to solve with `board_rsconnect`, currently it doesn't look like I can create subdirectory under `board_rsconnect`. 

Perhaps related to this: https://github.com/rstudio/pins/issues/348#issuecomment-822651739, you can see how the data sets are organized under each folder/sub folder. Can we have the same functionality on RStudio Connect?

**Comment by hadley** [comment]
@EKtheSage it will probably create a subdirectory in the on-disk cache, and will effectively act like a subdirectory remotely, but won't actually _be_ a subdirectory. This is a probably confusing answer, so a better question to ask would be: what properties of a subdirectory do you want a pin to possess?

**Comment by EKtheSage** [comment]
I produce multiple version of the same data set every month. Each data set has the same number of columns but has different values in the columns, due to the different parameters being applied to  it.

So, my use case is I want to correctly retrieve the data set based on the month and the parameters I specify. I think storing the date and parameter in the `metadata` is the better way to go, but I am unsure how to use `pin_read` to get the data set I want as `pin_read` always returns the most recent version.

```
pin_write(
  board = board,
  x = iris,
  name = 'Iris_Data',
  desc = 'Iris Take Two',
  metadata = list(
    Calendar_Date = '2021-06-30',
    parameter = 'alpha'
  )
)

pin_write(
  board = board,
  x = iris,
  name = 'Iris_Data',
  desc = 'Iris Take Two',
  metadata = list(
    Calendar_Date = '2021-06-30',
    parameter = 'beta'
  )
)

# unsure how to retrieve alpha version
```


```
pin_write(
  board = board,
  x = iris,
  name = 'Iris_Data_2021_06_30_alpha',
  desc = 'Iris Take Two',
)

pin_write(
  board = board,
  x = iris,
  name = 'Iris_Data_2021_06_30_beta',
  desc = 'Iris Take Two',
)

pin_read(board, name = 'Iris_Data_2021_06_30_alpha')
```

**Comment by hadley** [comment]
That use case sounds out of scope for pins right now. I'd suggest sticking with putting the params in the pin name.

**Comment by EKtheSage** [comment]
Thank you. Then what is the purpose of `metadata`  of a pin? Is it only useful when we call `pin_meta` to learn more about a particular pin?

**Comment by hadley** [comment]
It's now not entirely to me what this would imply, so I'm going to leave for now. Will eventually need to consider broadly, thinking about:

* Listing all pins in a "directory"
* How directories interact with the hierarchy implied by user names in `board_rsconnect()`
* Whether it would be useful to allow access to individual files from `pin_download()` (particularly for boards, like `board_kaggle()`, where we're reading from non-pin data sources).

**Comment by hadley** [comment]
@dgrtwo what if the subdirectory was a board parameter (as in #495)?

```R
board_marketing <- board_s3(prefix = "marketing")
board_sales <- board_s3(prefix = "sales")
board_marketing_expt <- board_s3(prefix = "marketing/experimental")
```

**Comment by hadley** [comment]
I think I've decided it's better to do this namespacing at the board level, rather than at the pin level.
