### ISSUE TITLE
Document using environment variables with pins on RStudio Connect

### ISSUE THREAD

**Issue by pyltime** [rstudio/pins#457]
The docs for using pins with RStudio Connect here: https://pins.rstudio.com/articles/boards-rsconnect.html are great, but don't cover what you should do if your pin needs access to environment variables for API keys, etc. This trips up users frequently since it's fairly different from how content, including our examples, work when running outside of Connect. It would be great to include a section for this, perhaps taking from our guide to using env variables with Connect here: https://db.rstudio.com/best-practices/deployment/#credentials-inside-environment-variables-in-rstudio-connect

**Comment by hadley** [comment]
Do you mean keys for `board_rsconnect()` itself?

**Comment by hadley** [comment]
(BTW the docs for this in the dev version of pins are at https://pins.rstudio.com/dev/reference/board_rsconnect.html).

**Comment by hadley** [comment]
Not sure if this fixes your issue or not, but I just totally rewrote the vignette to be simpler and to explain that with RSC 1.8.8 you don't need to set any env vars to publish a pin. Let me know if you think it needs more info than that.
