### ISSUE TITLE
`pins` images fail to load

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/pins#460]
There are several "broken" images on the main page [here](https://pins.rstudio.com/)

<img width="592" alt="2021-05-24_10-36-46" src="https://user-images.githubusercontent.com/31460023/119363588-f73e8100-bc7b-11eb-8c5f-81561fb0e5c1.png">

**Comment by hadley** [comment]
This is fixed in the dev version: https://pins.rstudio.com/dev/
