### ISSUE TITLE
board_register yaml error

### ISSUE THREAD

**Issue by kevin-m-kent** [rstudio/pins#463]
hi - when executing the following code I'm getting an error:

`pins::board_register_azure(container = "mycontainer",
                     account = "myaccount")`

Here is the error (removed my username):

`Error in yaml.load(string, error.label = error.label, ...) : 
  (C:\Users\me\AppData\Local\Temp\RtmpY9T4M9\file44ac704b35d8) Duplicate map key: 'type'`
  
 The odd thing is that this was working  fine for weeks and then all of a sudden it stopped. If I regenerate the key and try it works for 2-3 runs of the above code and then starts giving the same error again. So I'm guessing there is something happening with authenticating into the storage account but I'm not sure how to get rid of the error. It occurs now locally as well as on a virtual machine, so that's why I'm guessing it has something to do with the key. 

I've also tried reinstalling pins with no success, as well as restarting R and rstudio. I am also getting the same error if I use the generic board_register() function
 
 Do you have any ideas what I might try to fix this? Thank you!

**Comment by kevin-m-kent** [comment]
I believe I've solved my problem but I have no idea why. I deleted the data.txt file at the top level of the container and it magically started working again. I saw that it had a timestamp of last modified around when the board_register function stopped working, so I took a stab at deleting it and it seems to have cleared everything up.

**Comment by hadley** [comment]
azure is a legacy board, and I'll be rewriting the whole thing to use the modern API in #474. I think the source of this error is related to the legacy framework so it's unlikely reoccur.
