### ISSUE TITLE
Images broken on articles/use-cases.html

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/pins#487]
The article hrefs for: `Reuse Tidy Datasets` and `Update Plumber and Shiny Apps` are working but the images are missing on the [Use Cases page](https://pins.rstudio.com/articles/use-cases.html).

It looks like you're revamping a lot of the vignettes, so I'm not sure if this page is staying or not but wanted to raise the issue. Thanks!

![reuse](https://user-images.githubusercontent.com/29187501/130522718-d1a88caa-4d7a-4fd8-af1b-d49821d42957.png)

![update](https://user-images.githubusercontent.com/29187501/130522709-c04b8d97-5e97-42eb-8862-e18e42808d26.png)

**Comment by hadley** [comment]
It's been replaced by https://pins.rstudio.com/dev/articles/rsc.html
