### ISSUE TITLE
Onedrive/Sharepoint board?

### ISSUE THREAD

**Issue by hongooi73** [rstudio/pins#498]
Would there be interest in having the ability to put a board in Onedrive/Sharepoint?

There is an app from MS that syncs OD/SPO folders to your local drive, so in principle you don't need to do anything extra. However, this is only available for Windows and recent versions of MacOS. If you're on Linux, syncing can be tricky.

I can make a PR leveraging Microsoft365R as the OD/SPO backend for pins, if you feel it would be useful.

**Comment by hadley** [comment]
Yeah, that'd be awesome! There's some rough notes-to-self on creating a new board in #481, or if you implement the basics, I'm happy to finish off the details.

**Comment by hongooi73** [comment]
Working on a PR now, using `board_azure`, `board_s3` and `board_folder` for reference. Do you have a rough date on when you'll be submitting to CRAN?

**Comment by hadley** [comment]
I'm planning to come back to pins on Sept 13, and then probably aim for release 2 weeks later, all going well.
