### ISSUE TITLE
Add qs format

### ISSUE THREAD

**Issue by smingerson** [rstudio/pins#511]
Add [qs](https://github.com/traversc/qs) format to the package through qs in Suggests.  It is a great alternative to RDS for large, non-tabular data, thus expanding the types of data `pins` is useful for.

Happy to prepare a PR.

**Comment by hadley** [comment]
Yeah, that'd be nice. I think the PR should be straightforward, just use `check_installed()` to make sure is qs is installed; if it's not, `check_installed()` handles it nicely.
