### ISSUE TITLE
board_azure() with a prefix argument

### ISSUE THREAD

**Issue by ldanai** [rstudio/pins#518]
I found board_s3() with prefix argument is very useful concept #495. 

I am using both aws and azure.  board_azure() with prefix argument would also be useful for azure users.

Thanks for such powerful framework for sharing data across projects and teams.

**Comment by hongooi73** [comment]
Have you tried using a board with a nested path, like `board_azure(cont, "path/to/board")`?

The underlying storage machinery can handle such paths; if `board_azure` runs into problems I'll see if I can fix them up.

**Comment by ldanai** [comment]
Yes I have started using the dev version. The new API look quite friendly so I kindly of migrate my code to the new dev version. 

Let me try to `board_azure() ` for now. Thanks for suggesting.
