### ISSUE TITLE
Should addins be removed?

### ISSUE THREAD

**Issue by hadley** [rstudio/pins#525]
I didn't notice them earlier so they only work with the old API.

**Comment by juliasilge** [comment]
Could [this function be deprecated](https://github.com/rstudio/pins/blob/master/R/ui_addin.R) using lifecycle? Would that take care of it?

**Comment by hadley** [comment]
I was thinking about removing all the files in https://github.com/rstudio/pins/tree/master/inst/rstudio, but it probably should go through a deprecation cycle first if you think people use it.

**Comment by juliasilge** [comment]
Honestly I don't have much of a sense of how often these are used (my guess would be not much) so it's a matter of how conservative do you want to be.
