### ISSUE TITLE
board_azure cannot read old pins 

### ISSUE THREAD

**Issue by raisin-toast** [rstudio/pins#527]
We store our pins on azure and using the new API it seems as though we cannot read the pins that were created in the old version. We can access the pins container without a problem (using `AzureStor::blob_container` . We can also write and read in a newly created pin. 

However, when we try to read an old pin using `board_azure()`, we get an error saying `Error: Can't find version 'data.txt'`. 
Supplying the pins version to the function, using the `version` argument seems to make it work. However, we can't access the versions of the pins using `pin_versions`  - it returns the following tibble:

```
# A tibble: 4 x 3
  version   created hash 
  <chr>     <dttm>  <chr>
1 _versions NA      NA   
2 data.csv  NA      NA   
3 data.rds  NA      NA   
4 data.txt  NA      NA 
```

To add to the complication, using the legacy api function `board_register_azure()` now returns a 403 error. We use an access key to authenticate. 

Any advice on what to do will be greatly appreciated.

**Comment by hongooi73** [comment]
Is your old board versioned?

**Comment by raisin-toast** [comment]
Yes our old board was versioned. 

And the error we get is `Client error: (403) Forbidden. Failed to download remote file`.

**Comment by raisin-toast** [comment]
I don't think that is the case as other parts of our techstack that use the key are working. I have also spoken to admin and they haven't changed the key.

**Comment by hongooi73** [comment]
Can you share how your board was created? I can't figure out how to make a versioned board in Azure using the old pins package.

**Comment by hongooi73** [comment]
Nvm, I can reproduce the error with a non-versioned board.

**Comment by raisin-toast** [comment]
To setup with versions, we set up the container manually on `portal.azure.com` and then we register the board with this code: 
```
pins::board_register_azure(container = "container_name",
                           account = "account_name",
                           key = access_key,
                           versions = TRUE)
```
When I try to use legacy_azure I get this error `Error in !cache : invalid argument type`.  This is the same whether I leave the `cache` argument as null or as `pins::board_cache_path("azure")`

**Comment by hongooi73** [comment]
@hadley I think there is an actual bug here: if I use `legacy_azure` followed by `pin_get`, I get that error shown above. Or are you saying that legacy boards aren't accessible at all?

**Comment by hadley** [comment]
Reprex for me:

```R
remotes::install_version("pins", "0.4.5")
library(pins)

board_register_azure(
  container = "pins-legacy", 
  account = "pins2", 
  key = Sys.getenv("AZURE_PINS2_LEGACY_KEY")
)
pin(mtcars, "mtcars", board = "azure")

devtools::load_all()
board_register_azure(
  container = "pins-legacy", 
  account = "pins2", 
  key = Sys.getenv("AZURE_PINS2_LEGACY_KEY")
)
pin_get("mtcars", board = "azure")
```

To get this to work for me, I had to hack `azure_headers()` to not base64 decode my key, which seems odd.

**Comment by hadley** [comment]
Notice my error/warning is a little different:

```R
  Client error: (403) Forbidden. Failed to download remote file: https://pins2.blob.core.windows.net/pins-legacy/mtcars/data.rds
```

It looks like the path is ok, but maybe auth has failed?

**Comment by hadley** [comment]
And https://github.com/rstudio/pins/commit/7cde6e72486546a23939f2ed28c1dff0c605dc22

**Comment by hadley** [comment]
Oooh and you can make a reprex without using old pins:

```R
library(pins)
board <- legacy_azure("pins-legacy", "pins2", key = Sys.getenv("AZURE_PINS2_LEGACY_KEY"))
pin("mtcars", board = board)
```

**Comment by hadley** [comment]
Should be good now!
