### ISSUE TITLE
`board_azure` should allow setting the path to the board

### ISSUE THREAD

**Issue by hongooi73** [rstudio/pins#528]
Currently, `board_azure` doesn't have any facility to specify where the board is located inside the container. However, all storage services that AzureStor supports (file, blob, ADLS2) can have directories, like with a local disk, so there is no reason not to allow it.

I can make a PR for this.

**Comment by hongooi73** [comment]
This is basically the equivalent of specifying a prefix with S3; you can actually do the same with Azure, but using directory syntax seems more straightforward and also generalises to file and ADLS2 storage.

**Comment by hadley** [comment]
Yeah, a PR would be great.
