### ISSUE TITLE
Text encoding issues in online landing page

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/pins#541]
Here https://pins.rstudio.com/:

Apostrophe and quotation marks are not rendered correctly.

![snap](https://user-images.githubusercontent.com/19862384/137874602-868cedc1-4c0f-4694-b421-f309177e5307.png)

![snap2](https://user-images.githubusercontent.com/19862384/137874680-641b0206-a513-4bfe-ab9e-c2d8ecfa6198.png)

**Comment by hadley** [comment]
I don't see any problems locally, so I suspect this is a pkgdown problem: https://github.com/r-lib/pkgdown/issues/1895
