### ISSUE TITLE
Are some things too big to pin?

### ISSUE THREAD

**Issue by sellorm** [rstudio/pins#547]
There used to be a vignette with advice on appropriate data sizes for pins.

Could it, or something like it, be reinstated?

https://github.com/rstudio/pins/blob/8ff11887bf18b372f123454b70e2f6a7588c5745/vignettes/advanced-too-big.Rmd

It was a helpful rule of thumb for many when deciding what they should or should not pin.

**Comment by jthomasmock** [comment]
I wonder if this would be most appropriate under the Connect docs/Pro Tips? Tag @AshleyHenry15 

There's a small note in the `pins` Pro Tips:

> Pins are best suited for objects up to a few hundred megabytes in size.

**Comment by hadley** [comment]
I have the following in https://pins.rstudio.com/articles/pins.html:

> Note that when the data lives elsewhere, pins takes care of downloading and caching so that it’s only re-downloaded when needed. That said, most boards transmit pins over HTTP, and this is going to be slow and possibly unreliable for very large pins. As a general rule of thumb, we don’t recommend using pins with files over 500 MB. If you find yourself routinely pinning data larger that this, you might need to reconsider your data engineering pipeline.

Not sure how to make it more likely for people to find it at the right time.

**Comment by AshleyHenry15** [comment]
@jthomasmock - I will add the following note to the Pro Tip:
![2021-11-05_10-30-41](https://user-images.githubusercontent.com/31460023/140526925-efbc7ec2-8b62-4564-adaf-4c7a4ea229d9.png)

**Comment by hadley** [comment]
Thanks @AshleyHenry15!
