### ISSUE TITLE
Are you going to discontinue support for GCP buckets in the newer version? 

### ISSUE THREAD

**Issue by augustohassel** [rstudio/pins#548]

**Comment by Wesseldr** [comment]
+1 I was kind of surprised when it stopped working when i upgraded :-) But yes a I like'm too using gcloud :-)

**Comment by hadley** [comment]
@Wesseldr what do you mean it stopped working? the legacy board should continue to work. Can you please provide a reprex?

**Comment by hadley** [comment]
Closing in favour of https://github.com/rstudio/pins/issues/572
