### ISSUE TITLE
pin_write() access_type

### ISSUE THREAD

**Issue by vdamico** [rstudio/pins#551]
Hi,

I am currently updating my code to work with the new release of the package. We programmatically specify viewers for a given pin after uploading the pin since we don't want it to be accessible to everyone (and we have a lot of pins!), but I saw that `pin_write()` has an argument `access_type` and I was wondering if that could be used to set a handful of users as viewers? 

Thanks in advance!

**Comment by hadley** [comment]
`access_type` can only be "acl", "logged_in", or "all"; I think you'd want to use `acl`, but you'd still need to set up the list of users elsewhere (i.e. in the connect UI)

**Comment by vdamico** [comment]
Ok great, I'll look into this some more. Thank you for getting back to me on this!
