### ISSUE TITLE
Preview page code snippet

### ISSUE THREAD

**Issue by sellorm** [rstudio/pins#553]
The code snippet is very useful, but doesn't work out of the box

``` r
library(pins)
board <- board_rsconnect(server = "https://utah.company.com/rsc")
#> Error: `server` must be one of "cheddar", "utah.company.com", or "connect.companyservices.com".
pin_read(board, "mark.sellors/palmer_penguins")
#> Error in check_board(board, "pin_read()", "pin_get()"): object 'board' not found
```

<sup>Created on 2021-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It would be great if it did, or, if that's not possible, a brief explanation of the required parameters of a template snippet could be provided instead.

**Comment by sellorm** [comment]
Judging from the examples people have shared in other issues, I'd have to vote for "envvar".

**Comment by juliasilge** [comment]
I agree with @sellorm about `"envvar"` being the better option here for folks, based on what we already see people using and based on how people are encouraged to set up content on Connect in its docs.
