### ISSUE TITLE
Error: [EACCES] Failed to make directory '/....': permission denied

### ISSUE THREAD

**Issue by schmalte04** [rstudio/pins#568]
I have clean install of Ubuntu 20 with RStudio Server. After installing all packages and linux libs i got stuck with the pins package which is used in some productions routines.

i can register a github board, but i can't access as i did previously 
```

`board_register_github(repo = ".....", token = "......")

Mapping_table<-pin_get("Mapping-table", board="github")`
```

gives the following error:
Error: [EACCES] Failed to make directory '/....': permission denied

Seems like my Linux user is not allowed to create a temp folder name as the pin... Any ideas?

**Comment by hadley** [comment]
Can you please provide a reprex using the reprex package, even if you have to elide details from the code it produces?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
