### ISSUE TITLE
Search metadata with pin_search()

### ISSUE THREAD

**Issue by kmasiello** [rstudio/pins#573]
Metadata (and tags) are important for pin organization.  It would be helpful for`pin_search()` to extend into metadata. Common use cases would be to search by user, description, tag, or custom metadata field.

**Comment by hadley** [comment]
Unfortunately it's not possible with the current architecture because we'd have to either download each `.yaml` metafile individually (which would be slow) or build an index (which is v. hard without involvement on the server side).
