### ISSUE TITLE
pkgdown site has many unreadable characters

### ISSUE THREAD

**Issue by daattali** [rstudio/pins#575]
Not sure if this should be filed as a bug under {pkgdown} or here, but it seems the non-ASCII punctuation are causing problems on the pkgdown site.

See screenshot below for an example.

![image](https://user-images.githubusercontent.com/952340/145533535-88671832-21ad-41c9-b2f1-db67f36df28f.png)

**Comment by hadley** [comment]
It would be useful if you could provide the URL where you're seeing that.

**Comment by daattali** [comment]
It was on the landing page

**Comment by hadley** [comment]
Oh this is already fixed in the dev version: https://pins.rstudio.com/dev/
