### ISSUE TITLE
pin_reactive_read not checking existence of the pin

### ISSUE THREAD

**Issue by SaJaToGu** [rstudio/pins#584]
pin_reactive_read throws
Warning: Error in : Can't find pin called 'pinname'
Use `pin_list()` to see all available pins in this board

In shiny apps it might be possible that the pin is not existing directly but will be craeted within the app.
How to handle this?
Is it possible that the function is calling shiny::req(pin_exists(board, name)) itself?

**Comment by hadley** [comment]
I'd recommend calling `pin_exists()` yourself.
