### ISSUE TITLE
Be more explicit about how pins saves arrow data

### ISSUE THREAD

**Issue by sellorm** [rstudio/pins#605]
When people not using the `pins` package see a pin with an arrow data set, it is not immediately obvious what format that actually is.

For reference, the format used when `type = "arrow"` is actually 'feather'.

From the `pin_write()` help:

``` default
type               File type used to save x to disk. Must be one of "csv", "rds", "json", "arrow", or "qs". 
                       If not supplied will use json for bare lists and rds for everything else.
```

This is confusing for `arrow` users since there is no formal on-disk format called '.arrow'. Arrow users, generally use either '.parquet' or '.feather'.

`pins` should either:

1. Change this type name and file extension to 'feather'
2. Or be more explicit about the fact that what `pins` calls "arrow" is really "feather"  under the hood. 

If `pins` chooses to adopt the second of these approaches then it would be nice to highlight that it's feather in both the package help, as well as in the metadata somewhere.

This would hopefully reduce the support burden and help increase cross-language adoption.

**Comment by iainmwallace** [comment]
It would be useful to add an option to allow storing as parquet also

**Comment by nealrichardson** [comment]
For what it's worth, the [IANA extension for Arrow data](https://www.iana.org/assignments/media-types/application/vnd.apache.arrow.file) is `.arrow`, so that's not invalid, though .feather is also commonly used. See also https://arrow.apache.org/faq/. 

Parquet is a different format, though the arrow libraries can read and write Parquet.

**Comment by sellorm** [comment]
Thanks for the clarification @nealrichardson. The FAQ you linked recommends the `.arrow` extension without mentioning `.feather`. Would you recommendation therefore be that pins stays as it is?

Perhaps we could just tweak the docs a little to make things clearer for users.

**Comment by nealrichardson** [comment]
I'm not sure of the details, or whether the `type` parameter directly maps onto file extension. But saving files with a `.arrow` extension is not a problem.

**Comment by machow** [comment]
Thanks for all the discussion / resources. If I'm understanding, naming the pin type arrow is in line with how apache-arrow sees things (feather v2 is Arrow IPC format), and using `.arrow` extension too.

It seems like--based on the docs--if we had to choose between "arrow" and "feather", that "arrow" is where people are being steered toward (e.g. it recommends .arrow as the extension).

It seems like this might be the move for pins...

* python: add reading/writing pin type "arrow" to python pins, deprecate writing "feather".
* R: nothing needed
