### ISSUE TITLE
 Error: `meta$type` must be a character vector with  board_azure function

### ISSUE THREAD

**Issue by MislavSag** [rstudio/pins#614]
I am using `board_azure` function to retrieve data from bobs.

If I set cache to NULL, I get an error:
```
 Error: `meta$type` must be a character vector.
```
but when I use cashe=FALSE (which created FALSE folder in cwd directory), it works as expected.
It is hard to make reprex, since I would need  to provide creditentials.

**Comment by machow** [comment]
Hey--if you rune `cache_prune(days=0)` to delete your cached pins, does it resolve the issue? I wonder if it was cached with an older version of pins...

**Comment by MislavSag** [comment]
Sorry for late answer.
This has solved the problem.
Thanks.

**Comment by machow** [comment]
No problem--glad it worked!
