### ISSUE TITLE
Download problems for pins

### ISSUE THREAD

**Issue by jameshunterbr** [rstudio/pins#620]
I'm trying to download pins from this repository, but I get the following error.
> remotes::install_github("rstudio/pins")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

I have installed other packages via GitHub today successfully.
Sorry if I have put this in the wrong place.

**Comment by juliasilge** [comment]
I don't believe it is a problem with the pins GH repo. I was just able to install this again OK:

``` r
devtools::install_github("rstudio/pins", force = TRUE)
#> Downloading GitHub repo rstudio/pins@HEAD
#> 
#> * checking for file ‘/private/var/folders/hv/hzsmmyk9393_m7q3nscx1slc0000gn/T/RtmpXkyGJW/remotes645c3ad18d36/rstudio-pins-2a1a0d8/DESCRIPTION’ ... OK
#> * preparing ‘pins’:
#> * checking DESCRIPTION meta-information ... OK
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> Removed empty directory ‘pins/pkgdown’
#> * building ‘pins_1.0.1.9000.tar.gz’
```

<sup>Created on 2022-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It sounds like you probably have a problem with credentials for GitHub. You can read more about connecting to GitHub here:
https://happygitwithr.com/connect-intro.html

**Comment by jameshunterbr** [comment]
Thanks for the reminder. Indeed my PAT expired last week and I forgot to update it. All well now. See, Julia, you really are more competent that the brainless shriekers on Twitter are giving you credit for. I join with all the fans there responding to your tweet of yesterday.

[James Hunter](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1kw2dk)	[1kw2dk]
____________________________________
Prof. James R. Hunter, PhDBioinformática
Laboratório de Retrovirologia
Escola Paulista de Medicina
Universidade Federal de São Paulo
Cel: (55-11) 9-5327-5656
Rua Pedro de Toledo 669
6º Andar Fundos
04039-032 São Paulo, SP, BRASIL
Fone (11) 5576-4834
___________________________________

On June 3, 2022 at 15:13 GMT, Julia Silge ***@***.***> wrote:

I don't believe it is a problem with the pins GH repo. I was just able to install this again OK:
devtools::install_github("rstudio/pins", force = TRUE) #> Downloading GitHub repo ***@***.*** #>  #> * checking for file ‘/private/var/folders/hv/hzsmmyk9393_m7q3nscx1slc0000gn/T/RtmpXkyGJW/remotes645c3ad18d36/rstudio-pins-2a1a0d8/DESCRIPTION’ ... OK #> * preparing ‘pins’: #> * checking DESCRIPTION meta-information ... OK #> * checking for LF line-endings in source and make files and shell scripts #> * checking for empty or unneeded directories #> Removed empty directory ‘pins/pkgdown’ #> * building ‘pins_1.0.1.9000.tar.gz’

Created on 2022-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

It sounds like you probably have a problem with credentials for GitHub. You can read more about connecting to GitHub here:
https://happygitwithr.com/connect-intro.html

**Comment by juliasilge** [comment]
That is super kind @jameshunterbr! 🙌  Glad we got you sorted out.
