### ISSUE TITLE
register a github board could check for repo existence or offer to create one ?

### ISSUE THREAD

**Issue by cderv** [rstudio/pins#63]
Hi, 

I am just discovering the package and trying pin some data. 
I tried naively this thinking it would set up everything. 

```r
libary(pins)
board_register_github(repo = "cderv/pins-board")
```

There is no error,  warning or message but pinning does work because the repo does not exist yet in Github. 
```r
pin(iris, description = "The iris data set", board = "github")
```

I would have expected the registration process to warn about it or help create the repository. 

Also, the [github vignette ](https://rstudio.github.io/pins/articles/boards-github.html) does not precise explicitely to create the repository before registering. 

would this be some precision in documentation only or would you accept `board_register_github` to check for existence and if the repo does not exist, to warn and ask fr manual creation ?

**Comment by javierluraschi** [comment]
Makes a lot of sense, fixing and updating CRAN afterwards. Thanks for this feedback!
