### ISSUE TITLE
Documentation request - Access settings for RStudio Connect

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#71]
Hi,

It would be great if there could be some documentation on how to pin a resource that is used by a shiny app which is hosted on Connect

Does the access settings have to be manually set on the resource to mirror the access on the Shiny app?
If so, what error message would a user get if they don't have access to the resource but they do have access to the Shiny app?
Is there a way to automatically mirror the settings between the shiny app and the resource?

Thanks

Iain

Thanks

Iain

**Comment by iainmwallace** [comment]
In case it is useful, this is a minimal shiny app to read a table.

It seems that API key defines access to the repository, and anyone who has access to the app will consequently have access to the repository, which answers my questions above.


     #Run once to set up dataset
     pin(iris,name="my_iris",description = 'iris dataset',board = "rsconnect")
 
    library(DT)
    library(shiny)
    library(pins)

    board_register_rsconnect(key = Sys.getenv("RSTUDIO_CONNECT_API_KEY"),
                              server = Sys.getenv("RSTUDIO_CONNECT_SERVER"))


     ui <- fluidPage(DTOutput('tbl'))
      server <- function(input, output) {
      get_data<-reactive({
                pin_get("my_iris",board="rsconnect")
        })
    
     output$tbl = renderDT(
         get_data(), options = list(lengthChange = FALSE)
     )
     }

    # Run the application 
    shinyApp(ui = ui, server = server)

**Comment by javierluraschi** [comment]
There is a `pin_reactive()` helper function which retrieves a pin as a Shiny reactive. We also have an open PR to add some use-cases, one of which describes Shiny. The preview for this use case is available here:

https://deploy-preview-70--rstudio-pins-website.netlify.com/articles/use-cases/update-plumber-and-shiny-apps.html

**Comment by iainmwallace** [comment]
Awesome, thanks.

Only small suggestion I would add to the documentation app is to specify the API key parameter. It was a point that tripped us a couple of times and also helps clarify that the resource is being accessed by the owner of the API key and not the user accessing the Shiny app

**Comment by javierluraschi** [comment]
Makes sense; however, most users will try this first in their local environment and will get confused by the key parameter... so planning to keep this as it is for now.
