### ISSUE TITLE
Documentation request: Example code to report usage of pins on Connect

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#75]
Hi,

It would be very useful to have some examples on how to track usage metrics of pins on Connect

For example, for a pin that I created I would like to know 
- when was it last accessed
- who was it accessed by
- is it being used by any other resource (Shiny/Markdown)

As an administrator I would like to know
- what pins are currently on the system
- who created them
- who is using them
- how much space is being used

Thanks 

Iain

**Comment by javierluraschi** [comment]
Right, this makes sense but would have to be specific to each board, GitHub boards might have different attributes, etc. This could be realted to https://github.com/rstudio/pins/issues/76, maybe `pin_metadata()` retrieves both: User metadata and Board metadata.

In any case, should be able to expose these attributes somehow.

**Comment by javierluraschi** [comment]
There is more functionality we can add here, but as a start, next CRAN release (pins 0.3.0) adds support for `pin_info()` and `pin_find(extended = TRUE)` to help advanced users manage their pins in RStudio Connect and other boards.

**Comment by javierluraschi** [comment]
Looks like `pin_info()` provides the functionality we need, at least for now.
