### ISSUE TITLE
Suggestion: Ability to add custom meta data 

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#76]
It would be very useful to be able to add custom meta data as key value pairs to a pin that others could use to find. 
For example, 
pin1 I would like to store Project=”ABC”, Target=”123”, Compound=”XYZ”, TeamContact=”Barry”
pin2 I would like to store Project=”ABCD”, Target=”1234”, Compound=”XYZ”, TeamContact=”Aoife”

It would also be nice to add tags that Connect uses.

**Comment by javierluraschi** [comment]
There are two parts in this...
1) Should be straightforward to implement support for metadata for `pin()` and `pin_get()`, maybe with a helper function like `pin_metadata()` to retrieve a pin metadata.
2) Is not straightforward to retrieve metadata when doing `pin_find()`.

So, @iainmwallace, could you give an example of how you were planning to use the metadata? Is it only to retrieve it after storing something? Or where you hoping to be able to filter pins as well in `pin_find()` using metadata?

**Comment by iainmwallace** [comment]
Ideally I would be able to find all datasets that contain a specific tag or a specific tag value.

Potential use cases, depending on tags used
- tag datasets with related datasets to help a future analyst find all the relevant data
- retrieve all datasets from a particular project
- retrieve all datasets that contain a specific column

**Comment by rspreafico-vir** [comment]
Having tags would be truly awesome. As the number of pins in a board increase, tags become essential for organization and search. Creating more boards would not solve the issue since boards behave like folders in a file system, imposing a rigid segregation, whereas the combinatorics of tags is much more flexible. Thanks for considering adding tags to a future release!

**Comment by javierluraschi** [comment]
Moving to next release, but still on my mind.

**Comment by iainmwallace** [comment]
Great! The organization certainly becomes more important as the number of pins deployed increases - they are such a handy feature :)

**Comment by javierluraschi** [comment]
Great suggestion but not likely to be implemented anytime soon, so closing to help manage GitHub issues.
