### ISSUE TITLE
Suggestion: allow ability to provide example command to read in file pin

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#77]
pin_get("iwallace/diamonds", board = "rsconnect")
could become
pinned_diamonds<-readRDS(pin_get("iwallace/diamonds", board = "rsconnect"))

This would improve the UX on Connect for the person consuming the resource as they can directly copy and paste

**Comment by javierluraschi** [comment]
This is only required if someone runs:

```r
saveRDS(ggplot2::diamonds, "diamons.rds")
pin("diamons.rds", "diamonds", board = "rsconnect")
```

Which does indeed require,

```r
readRDS(pin_get("diamonds", board = "rsconnect"))
```

However, we ca also run:

```r
pin(ggplot2::diamonds, "diamonds", board = "rsconnect")
```

Which does not require `readRDS`:

```r
pin_get("diamonds", board = "rsconnect")
```

Or to avoid writing a CSV, 

```r
pin(I(ggplot2::diamonds), "diamonds", board = "rsconnect")
```

Which would not require manually reading the RDS manually,

```r
pin_get("diamonds", board = "rsconnect")
```

If this is a reasonable workaround, feel free to close this issue; otherwise, let us know to take a closer look!

**Comment by iainmwallace** [comment]
Perhaps this example might explain the potential issue a bit better, which is about the UX of the consumer from Connect

 User 1 shares a parquet file for a dataset of interest 
    arrow::write_parquet(ggplot2::diamonds,"test.parquet")
    pin("test.parquet",name="parquet_test",board="rsconnect")

 User 2 views the file on connect and copies the commands to retrieve into their console
    # Register RStudio Connect
    library(pins)
    board_register("rsconnect", server = "https://rconnect-dev.redda.celgene.com") # will this 
    work for all users? 

    # Retrieve Pin
    pin_get("iwallace/parquet_test", board = "rsconnect")

 User 2 needs to know two things to get the contents of this file into their environment
 1. What a parquet file is?
 2. How best to read in the contents?

User 2 then needs to type in the commands which seems counterintuitive from the nice welcoming screen in Connect that shows how to retrieve the data
