### ISSUE TITLE
Suggestion: Allow the option to create multiple boards on Connect

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#78]
For example, it would be useful for teams to be able to create a team board

**Comment by javierluraschi** [comment]
We might be able to implement this using RStudio Connect tags.

**Comment by javierluraschi** [comment]
Not sure yet how to implement this one, pushing out to be implemented later on.

**Comment by javierluraschi** [comment]
Definitely a feature request, closing since we are not realistically working on this one in the short term... but likely to be needed as `pins` adoption keeps wrowing.
