### ISSUE TITLE
Support retrieving public RStudio Connect pins without authentication

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/pins#83]

**Comment by slopp** [comment]
@javierluraschi this issue has come up now that pins is gaining traction with customers because it is making it harder for our SE/CS teams to demo. Would you be amenable to taking another look?

**Comment by akgold** [comment]
Another request here: https://community.rstudio.com/t/pins-access-for-non-licenced-users/56402

**Comment by colearendt** [comment]
A few ideas:

- I.e. pins seems to "search the board, find the content, get it"... when you're unauthorized, "search the board / find the content" cannot work. You just have to go straight to "get it", but Connect does not have a notion of doing that unless you have (1) the guid, (2) the ID, (3) the vanity URL

- Maybe Server.EnableSitemap would provide a workaround: https://docs.rstudio.com/connect/admin/appendix-configuration.html#Server.EnableSitemap
We could check auth with __api__/me and then see if the sitemap exists.

- Alternatively, pins could have a way to specify the GUID / ID / Vanity URL if you need to refer to a pin by that

**Comment by cwthom** [comment]
To add support for this (I raised the request linked by akgold above). For me the ideal interface would be something:

```
library(pins)
pin_get(url = "https://rsconnect-server/rsc/pins/ID", board = NULL)
```

and raise an error if the access setting for the pin is restricted to named users or the url is undiscoverable.
