### ISSUE TITLE
Support cloud storage buckets as boards

### ISSUE THREAD

**Issue by jduckles** [rstudio/pins#84]
It would be nice to have support for read/write to/from boards stored in cloud storage buckets. 

Supporting the major cloud providers:

1. Amazon S3 
2. Microsoft Blob Storage
3. Google Cloud storage. 

Based [on this tweet](https://twitter.com/javierluraschi/status/1185000235065466880), please vote on the cloud provider(s) you'd most like to see supported with a thumbs-up.

**Comment by jduckles** [comment]
Amazon S3

**Comment by jduckles** [comment]
Microsoft Blob Storage

**Comment by jduckles** [comment]
Google Cloud Storage

**Comment by iainmwallace** [comment]
This is a great idea - it would also be very nice if one could manage a cloud bucket board through RStudio Connect, or configure RStudio Connect to use a cloud bucket in the back ground to store boards

**Comment by javierluraschi** [comment]
Implement!
